import AppLayout from '@/Layouts/AppLayout';
import { Head, Link } from '@inertiajs/react';
import axios from 'axios';
import { Check, ChevronLeft, FileText, MapPin, Plus, Route, Sparkles } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';

interface Task { id: number; title: string; completed_at?: string | null; due_at?: string | null; priority: string; assignee?: { name: string }; }
interface Attachment { id: number; label?: string | null; external_url?: string | null; reference_code?: string | null; kind: string; media?: { uuid: string; display_title?: string | null; original_filename: string }; }
interface Candidate { id: number; uuid: string; display_title?: string | null; original_filename: string; taken_at?: string | null; }
interface EventDetail { uuid: string; title: string; description?: string | null; type: string; starts_at: string; ends_at?: string | null; place_name?: string | null; departure_at?: string | null; trip_id?: number | null; my_response?: 'accepted'|'tentative'|'declined'|null; tasks: Task[]; attachments: Attachment[]; budget?: Record<string, string>; route_variants?: Array<{ id:number; title:string; strategy:string; is_selected:boolean; estimated_minutes?:number; estimated_cost?:number; currency?:string }>; }

export default function CalendarShow({ eventUuid }: { eventUuid: string }) {
    const [event, setEvent] = useState<EventDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
    const [taskTitle, setTaskTitle] = useState(''); const [attachment, setAttachment] = useState({ label: '', external_url: '', reference_code: '' }); const [candidates, setCandidates] = useState<Candidate[]>([]); const [chosen, setChosen] = useState<number[]>([]); const [story, setStory] = useState<string>('');
    const load = async () => { setLoading(true); try { const r = await axios.get(`/api/v1/calendar/events/${eventUuid}`); setEvent(r.data); } catch (e: any) { setError(e.response?.status === 404 ? 'Akce nebyla nalezena nebo k ní nemáte přístup.' : 'Akci se nepodařilo načíst.'); } finally { setLoading(false); } };
    useEffect(() => { load(); }, [eventUuid]);
    const submitTask = async (e: FormEvent) => { e.preventDefault(); if (!taskTitle.trim()) return; await axios.post(`/api/v1/calendar/events/${eventUuid}/tasks`, { title: taskTitle }); setTaskTitle(''); load(); };
    const toggleTask = async (task: Task) => { await axios.patch(`/api/v1/calendar/events/${eventUuid}/tasks/${task.id}`, { completed: !task.completed_at }); load(); };
    const submitAttachment = async (e: FormEvent) => { e.preventDefault(); await axios.post(`/api/v1/calendar/events/${eventUuid}/attachments`, attachment); setAttachment({ label:'', external_url:'', reference_code:'' }); load(); };
    const getSuggestions = async () => { const r = await axios.get(`/api/v1/calendar/events/${eventUuid}/media-suggestions`); setCandidates(r.data.candidates ?? []); };
    const attachSelected = async () => { if (!chosen.length) return; await axios.post(`/api/v1/calendar/events/${eventUuid}/media-suggestions`, { media_ids: chosen }); setChosen([]); load(); };
    const createStory = async () => { const r = await axios.post(`/api/v1/calendar/events/${eventUuid}/story`); setStory(r.data.summary); };
    const respond = async (response: 'accepted'|'tentative'|'declined') => { const r = await axios.post(`/api/v1/calendar/events/${eventUuid}/response`, { response }); setEvent(r.data); };
    if (loading) return <AppLayout><main className="p-6 text-[var(--color-text-secondary)]">Načítám akci…</main></AppLayout>;
    if (!event) return <AppLayout><main className="p-6"><p className="text-red-300">{error}</p><Link href="/calendar" className="mt-3 inline-block text-[var(--color-accent)]">← Zpět do kalendáře</Link></main></AppLayout>;
    const date = new Intl.DateTimeFormat('cs-CZ', { dateStyle:'full', timeStyle:'short' }).format(new Date(event.starts_at));
    return <AppLayout><Head title={event.title}/><main className="mx-auto max-w-5xl p-4 sm:p-6"><Link href="/calendar" className="mb-4 inline-flex items-center gap-1 text-sm text-[var(--color-accent)]"><ChevronLeft size={16}/> Kalendář</Link>
        <header className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-5"><p className="text-xs font-medium uppercase tracking-wide text-[var(--color-accent)]">{event.type}</p><h1 className="mt-1 text-2xl font-semibold text-white">{event.title}</h1><p className="mt-2 text-sm text-[var(--color-text-secondary)]">{date}{event.place_name ? ` · ${event.place_name}` : ''}</p>{event.description && <p className="mt-3 whitespace-pre-wrap text-sm text-[var(--color-text-secondary)]">{event.description}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={createStory} className="inline-flex items-center gap-2 rounded-lg border border-[var(--color-border)] px-3 py-2 text-sm text-white"><Sparkles size={15}/> Vytvořit příběh</button><a href={`/api/v1/calendar/events/${eventUuid}/ics`} className="inline-flex items-center gap-2 rounded-lg border border-[var(--color-border)] px-3 py-2 text-sm text-white">ICS kalendář</a>{event.trip_id && <Link href={`/trips/${event.trip_id}/plan`} className="inline-flex items-center gap-2 rounded-lg bg-[var(--color-accent)] px-3 py-2 text-sm text-white"><Route size={15}/> Plán cesty</Link>}</div><div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-xs text-[var(--color-text-secondary)]">Moje účast:</span>{([['accepted','Ano'],['tentative','Možná'],['declined','Ne']] as const).map(([value,label]) => <button key={value} onClick={() => respond(value)} className={`min-h-9 rounded-lg px-3 text-xs ${event.my_response === value ? 'bg-[var(--color-accent)] text-white' : 'border border-[var(--color-border)] text-[var(--color-text-secondary)]'}`}>{label}</button>)}</div>{story && <p className="mt-3 rounded-lg bg-[var(--color-accent)]/10 p-3 text-sm text-[var(--color-text-secondary)]">{story}</p>}</header>
        <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><h2 className="font-semibold text-white">Společný checklist</h2><form onSubmit={submitTask} className="mt-3 flex gap-2"><input value={taskTitle} onChange={e => setTaskTitle(e.target.value)} placeholder="Přidat úkol" className="min-w-0 flex-1 rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-sm text-white"/><button className="rounded-lg bg-[var(--color-accent)] p-2 text-white" aria-label="Přidat úkol"><Plus size={16}/></button></form><div className="mt-3 space-y-2">{event.tasks.map(task => <button key={task.id} onClick={() => toggleTask(task)} className="flex w-full items-center gap-3 rounded-lg border border-[var(--color-border)] p-2 text-left"><span className={`flex h-5 w-5 items-center justify-center rounded border ${task.completed_at ? 'border-[var(--color-accent)] bg-[var(--color-accent)]' : 'border-[var(--color-text-secondary)]'}`}>{task.completed_at && <Check size={13}/>}</span><span className={`flex-1 text-sm ${task.completed_at ? 'text-[var(--color-text-secondary)] line-through' : 'text-white'}`}>{task.title}</span></button>)}{!event.tasks.length && <p className="text-sm text-[var(--color-text-secondary)]">Zatím žádné úkoly.</p>}</div></section>
        <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><h2 className="font-semibold text-white">Odjezd a bezpečnost</h2><div className="mt-3 space-y-3 text-sm text-[var(--color-text-secondary)]">{event.departure_at ? <p><strong className="text-white">Vyrazit:</strong> {new Intl.DateTimeFormat('cs-CZ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(event.departure_at))}</p> : <p>Přidejte časovou rezervu odjezdu pro chytrou připomínku.</p>}<p className="rounded-lg border border-[var(--color-border)] p-3"><MapPin className="mr-2 inline text-[var(--color-accent)]" size={15}/>{event.place_name || 'Místo ještě není vyplněno'}<br/><span className="text-xs">Nouzová karta: sdílejte jen adresu a ověřené rezervace, nikdy citlivé doklady.</span></p>{event.route_variants?.filter(v => v.is_selected).map(v => <p key={v.id}>Vybraná varianta: <strong className="text-white">{v.title}</strong>{v.estimated_minutes ? ` · ${v.estimated_minutes} min` : ''}</p>)}</div></section>
        <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><h2 className="font-semibold text-white">Rezervace a přílohy</h2><form onSubmit={submitAttachment} className="mt-3 space-y-2"><input value={attachment.label} onChange={e => setAttachment({...attachment,label:e.target.value})} placeholder="Název (např. hotel)" className="w-full rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-sm text-white"/><input value={attachment.external_url} onChange={e => setAttachment({...attachment,external_url:e.target.value})} placeholder="Bezpečný odkaz https://" type="url" className="w-full rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-sm text-white"/><input value={attachment.reference_code} onChange={e => setAttachment({...attachment,reference_code:e.target.value})} placeholder="Referenční kód" className="w-full rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-sm text-white"/><button className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-sm text-white">Uložit rezervaci</button></form><div className="mt-3 space-y-2">{event.attachments.map(item => <div key={item.id} className="rounded-lg border border-[var(--color-border)] p-2 text-sm"><FileText className="mr-2 inline text-[var(--color-accent)]" size={14}/>{item.label || item.media?.display_title || item.media?.original_filename || item.reference_code || 'Příloha'} {item.external_url && <a className="ml-2 text-[var(--color-accent)]" href={item.external_url} rel="noreferrer" target="_blank">Otevřít</a>}</div>)}</div></section>
        <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><h2 className="font-semibold text-white">Vzpomínky z akce</h2><button onClick={getSuggestions} className="mt-3 rounded-lg border border-[var(--color-border)] px-3 py-2 text-sm text-white">Najít vhodná média</button>{candidates.length > 0 && <><div className="mt-3 max-h-48 space-y-1 overflow-auto">{candidates.map(media => <label key={media.id} className="flex items-center gap-2 rounded p-1 text-sm text-[var(--color-text-secondary)]"><input type="checkbox" checked={chosen.includes(media.id)} onChange={() => setChosen(current => current.includes(media.id) ? current.filter(id => id !== media.id) : [...current, media.id])}/>{media.display_title || media.original_filename}</label>)}</div><button onClick={attachSelected} className="mt-2 rounded-lg bg-[var(--color-accent)] px-3 py-2 text-sm text-white">Přidat vybrané</button></>}</section></div>
    </main></AppLayout>;
}
