import { Link } from '@inertiajs/react';
import axios from 'axios';
import { Check, ChefHat, ClipboardCopy, Plus, ShoppingBasket, Trash2, Users, Wallet } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';

interface TripDayOption { id:number; date:string; title?:string; }
interface Member { id:number; name:string; }
interface RecipeOption { uuid:string; title:string; category:string; base_servings:number; total_minutes:number; estimated_cost?:number|null; currency:string; }
interface Meal { uuid:string; recipe:{uuid:string;title:string;category:string;cover_url?:string|null}; meal_type:string; planned_for:string; servings:number; status:string; notes?:string|null; estimated_cost?:number|null; currency:string; cooking_session_uuid?:string|null; }
interface ShoppingItem { key:string; name:string; unit?:string|null; display_quantity?:string|null; quantity_notes:string[]; preparations:string[]; sources:string[]; is_pantry:boolean; is_optional:boolean; is_checked:boolean; assigned_to?:Member|null; note?:string|null; }
interface MealPlan { meals:Meal[]; shopping:ShoppingItem[]; members:Member[]; available_recipes:RecipeOption[]; summary:{meals:number;servings:number;shopping_items:number;checked_items:number;estimated_cost:number;currency:string;unconverted_costs:number;budget?:{limit:number|null;planned:number;remaining:number|null;usage_percent:number|null}|null}; }

const mealLabels:Record<string,string>={breakfast:'Snídaně',lunch:'Oběd',dinner:'Večeře',snack:'Svačina',picnic:'Piknik',other:'Jiné'};
const statusLabels:Record<string,string>={planned:'naplánováno',prepared:'uvařeno',skipped:'vynecháno'};
const field='min-h-10 min-w-0 rounded-xl border border-[var(--color-border)] bg-black/10 px-3 text-xs text-white focus:border-amber-400 focus:outline-none';

export default function MealPlanPanel({eventUuid,tripId,days=[],onChanged}:{eventUuid?:string;tripId?:number;days?:TripDayOption[];onChanged?:()=>void|Promise<void>}) {
    const endpoint=eventUuid?`/api/v1/calendar/events/${eventUuid}/meal-plan`:`/api/v1/trips/${tripId}/meal-plan`;
    const shoppingEndpoint=(key:string)=>eventUuid?`/api/v1/calendar/events/${eventUuid}/meal-shopping/${key}`:`/api/v1/trips/${tripId}/meal-shopping/${key}`;
    const [data,setData]=useState<MealPlan|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [expanded,setExpanded]=useState(true);
    const [form,setForm]=useState({recipe_uuid:'',meal_type:'dinner',servings:'2',trip_day_id:'',time:'18:00',notes:''});
    const load=async()=>{try{const response=await axios.get(endpoint);setData(response.data);setError('');setForm(current=>({...current,recipe_uuid:current.recipe_uuid||response.data.available_recipes?.[0]?.uuid||'',servings:current.recipe_uuid?current.servings:String(response.data.available_recipes?.[0]?.base_servings??2),trip_day_id:current.trip_day_id||String(days[0]?.id??'')}));}catch(reason:any){if(reason.response?.status!==503)setError(reason.response?.data?.message??'Jídelní plán se nepodařilo načíst.');}finally{setLoading(false);}};
    useEffect(()=>{load();},[endpoint]);
    const selected=useMemo(()=>data?.available_recipes.find(item=>item.uuid===form.recipe_uuid),[data,form.recipe_uuid]);
    const add=async(event:FormEvent)=>{event.preventDefault();if(!form.recipe_uuid)return;setBusy(true);setError('');try{const day=days.find(item=>String(item.id)===form.trip_day_id);const payload:any={recipe_uuid:form.recipe_uuid,meal_type:form.meal_type,servings:Number(form.servings),notes:form.notes||undefined};if(tripId){payload.trip_day_id=Number(form.trip_day_id);payload.planned_for=day?`${day.date}T${form.time||'18:00'}`:undefined;}const response=await axios.post(endpoint,payload);setData(response.data);setForm(current=>({...current,notes:''}));setNotice('Jídlo je propojené s receptem, kalendářem, přípravou a nákupem.');await onChanged?.();}catch(reason:any){setError(reason.response?.data?.message??'Jídlo se nepodařilo naplánovat.');}finally{setBusy(false);}};
    const updateItem=async(item:ShoppingItem,patch:Record<string,unknown>)=>{setBusy(true);try{const response=await axios.patch(shoppingEndpoint(item.key),patch);setData(response.data);await onChanged?.();}catch(reason:any){setError(reason.response?.data?.message??'Nákupní položku se nepodařilo změnit.');}finally{setBusy(false);}};
    const remove=async(meal:Meal)=>{if(!window.confirm(`Odebrat ${meal.recipe.title} z plánu?`))return;setBusy(true);try{await axios.delete(`/api/v1/planned-meals/${meal.uuid}`);await load();await onChanged?.();}catch(reason:any){setError(reason.response?.data?.message??'Jídlo se nepodařilo odebrat.');}finally{setBusy(false);}};
    const copy=async()=>{if(!data)return;const text=data.shopping.filter(item=>!item.is_checked).map(item=>`☐ ${item.display_quantity?item.display_quantity+' ':''}${item.unit?item.unit+' ':''}${item.name}${item.is_pantry?' (ověřit zásobu)':''}`).join('\n');try{await navigator.clipboard.writeText(text);setNotice('Zbývající nákup je zkopírovaný.');}catch{setError('Seznam se nepodařilo zkopírovat.');}};
    if(!loading&&!data&&!error)return null;
    const progress=data?.summary.shopping_items?Math.round(data.summary.checked_items/data.summary.shopping_items*100):0;
    return <section className="mb-5 overflow-hidden rounded-2xl border border-amber-400/25 bg-gradient-to-br from-amber-500/10 via-[var(--color-bg-card)] to-orange-500/5">
        <button type="button" onClick={()=>setExpanded(value=>!value)} className="flex min-h-16 w-full items-center gap-3 p-4 text-left"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-500/15 text-amber-200"><ChefHat size={20}/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-white">Jídlo, vaření a společný nákup</span><span className="block text-[10px] text-[var(--color-text-secondary)]">{data?`${data.summary.meals} jídel · ${data.summary.checked_items}/${data.summary.shopping_items} položek · ${data.summary.estimated_cost.toLocaleString('cs-CZ')} ${data.summary.currency}`:'Načítám propojený plán…'}</span></span><span className="text-xs text-amber-100">{expanded?'−':'+'}</span></button>
        {expanded&&<div className="border-t border-amber-300/15 p-4 sm:p-5">
            {error&&<p className="mb-3 rounded-xl bg-red-500/10 p-3 text-xs text-red-200">{error}</p>}{notice&&<p className="mb-3 rounded-xl bg-emerald-500/10 p-3 text-xs text-emerald-100">{notice}</p>}
            {data&&<><form onSubmit={add} className="grid gap-2 sm:grid-cols-2 lg:grid-cols-6"><select required value={form.recipe_uuid} onChange={event=>{const recipe=data.available_recipes.find(item=>item.uuid===event.target.value);setForm({...form,recipe_uuid:event.target.value,servings:String(recipe?.base_servings??2)});}} className={`${field} sm:col-span-2 lg:col-span-2`}><option value="">Vybrat recept</option>{data.available_recipes.map(recipe=><option key={recipe.uuid} value={recipe.uuid}>{recipe.title}</option>)}</select><select value={form.meal_type} onChange={event=>setForm({...form,meal_type:event.target.value})} className={field}>{Object.entries(mealLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input required type="number" min="0.25" max="1000" step="0.25" value={form.servings} onChange={event=>setForm({...form,servings:event.target.value})} aria-label="Počet porcí" className={field}/>{tripId&&<><select required value={form.trip_day_id} onChange={event=>setForm({...form,trip_day_id:event.target.value})} className={field}>{days.map((day,index)=><option key={day.id} value={day.id}>Den {index+1} · {new Date(`${day.date}T12:00:00`).toLocaleDateString('cs-CZ',{day:'numeric',month:'numeric'})}</option>)}</select><input type="time" value={form.time} onChange={event=>setForm({...form,time:event.target.value})} className={field}/></>}<input value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})} placeholder="Poznámka k přípravě" className={`${field} sm:col-span-2 lg:col-span-5`}/><button disabled={busy||!form.recipe_uuid} className="inline-flex min-h-10 items-center justify-center gap-1 rounded-xl bg-amber-500 px-3 text-xs font-semibold text-black disabled:opacity-40"><Plus size={14}/>Přidat</button></form>{selected&&<p className="mt-2 text-[10px] text-[var(--color-text-secondary)]">{selected.total_minutes} min · základ {selected.base_servings} porce{selected.estimated_cost!=null?` · odhad ${Number(selected.estimated_cost).toLocaleString('cs-CZ')} ${selected.currency}`:''}</p>}
            <div className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(300px,.9fr)]"><div><div className="mb-2 flex items-center justify-between"><h3 className="text-xs font-semibold text-white">Jídelní plán</h3><span className="inline-flex items-center gap-1 text-[10px] text-amber-100"><Wallet size={12}/>{data.summary.estimated_cost.toLocaleString('cs-CZ')} {data.summary.currency}</span></div><div className="space-y-2">{data.meals.map(meal=><article key={meal.uuid} className="flex items-center gap-3 rounded-xl border border-[var(--color-border)] bg-black/10 p-2.5">{meal.recipe.cover_url?<img src={meal.recipe.cover_url} loading="lazy" alt="" className="h-12 w-12 shrink-0 rounded-lg object-cover"/>:<span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-amber-500/10">🍲</span>}<div className="min-w-0 flex-1"><Link href={`/recipes/${meal.recipe.uuid}`} className="block truncate text-sm font-medium text-white hover:text-amber-100">{meal.recipe.title}</Link><p className="text-[10px] text-[var(--color-text-secondary)]">{mealLabels[meal.meal_type]??meal.meal_type} · {meal.servings} porce · {new Date(meal.planned_for).toLocaleString('cs-CZ',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'})} · {statusLabels[meal.status]??meal.status}</p></div><button disabled={busy} onClick={()=>remove(meal)} aria-label="Odebrat jídlo" className="p-2 text-[var(--color-text-secondary)] hover:text-red-300"><Trash2 size={14}/></button></article>)}{!data.meals.length&&<p className="rounded-xl border border-dashed border-[var(--color-border)] p-4 text-center text-xs text-[var(--color-text-secondary)]">Vyberte první recept. Suroviny a příprava se propojí automaticky.</p>}</div>{data.summary.budget&&<div className="mt-3 rounded-xl border border-emerald-400/20 bg-emerald-500/5 p-3"><div className="flex justify-between text-[10px] text-emerald-100"><span>Rozpočet na jídlo</span><span>{data.summary.budget.usage_percent??0}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-black/20"><div className={`h-full rounded-full ${(data.summary.budget.usage_percent??0)>100?'bg-red-400':'bg-emerald-400'}`} style={{width:`${Math.min(100,data.summary.budget.usage_percent??0)}%`}}/></div><p className="mt-2 text-[10px] text-[var(--color-text-secondary)]">Zbývá {data.summary.budget.remaining?.toLocaleString('cs-CZ')??'—'} {data.summary.currency}</p></div>}</div>
            <div><div className="mb-2 flex items-center justify-between gap-2"><div><h3 className="flex items-center gap-1 text-xs font-semibold text-white"><ShoppingBasket size={14} className="text-amber-200"/>Společný nákup</h3><p className="text-[10px] text-[var(--color-text-secondary)]">Zaškrtnutí se propíše do {tripId?'balení cesty':'úkolů akce'}.</p></div><button onClick={copy} disabled={!data.shopping.length} className="inline-flex min-h-8 items-center gap-1 rounded-lg border border-[var(--color-border)] px-2 text-[10px] text-white disabled:opacity-40"><ClipboardCopy size={12}/>Kopírovat</button></div><div className="mb-3 h-1.5 overflow-hidden rounded-full bg-black/20"><div className="h-full rounded-full bg-amber-400 transition-all" style={{width:`${progress}%`}}/></div><div className="max-h-80 space-y-1.5 overflow-y-auto pr-1">{data.shopping.map(item=><div key={item.key} className={`rounded-xl border p-2 ${item.is_checked?'border-emerald-400/15 bg-emerald-500/5':'border-[var(--color-border)] bg-black/10'}`}><div className="flex items-start gap-2"><button disabled={busy} onClick={()=>updateItem(item,{is_checked:!item.is_checked})} className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded border ${item.is_checked?'border-emerald-400 bg-emerald-500/20 text-emerald-200':'border-[var(--color-text-secondary)]'}`}>{item.is_checked&&<Check size={12}/>}</button><div className="min-w-0 flex-1"><p className={`text-xs ${item.is_checked?'text-[var(--color-text-secondary)] line-through':'text-white'}`}>{item.display_quantity&&`${item.display_quantity} `}{item.unit&&`${item.unit} `}{item.name}{item.is_optional&&<span className="ml-1 text-[9px] text-[var(--color-text-secondary)]">volitelné</span>}</p><p className="truncate text-[9px] text-[var(--color-text-secondary)]">{item.sources.join(', ')}{item.is_pantry?' · ověřit doma':''}</p></div><label className="relative shrink-0"><Users size={13} className="pointer-events-none absolute left-2 top-2 text-[var(--color-text-secondary)]"/><select value={item.assigned_to?.id??''} onChange={event=>updateItem(item,{assigned_to:event.target.value?Number(event.target.value):null})} aria-label={`Kdo koupí ${item.name}`} className="min-h-7 max-w-28 rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-secondary)] pl-7 pr-1 text-[9px] text-white"><option value="">společně</option>{data.members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label></div></div>)}{!data.shopping.length&&<p className="py-4 text-center text-xs text-[var(--color-text-secondary)]">Suroviny se objeví po přidání jídla.</p>}</div></div></div></>}</div>}
    </section>;
}
