import axios from 'axios';
import { GripVertical, Plus, Save, Trash2, X } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';

type IngredientDraft = { section:string; name:string; quantity:string|number; unit:string; quantity_note:string; is_scalable:boolean; is_optional:boolean; is_pantry:boolean; preparation:string; substitutes:string };
type StepDraft = { title:string; instruction:string; timer_seconds:string|number; temperature:string|number; temperature_unit:'C'|'F'; equipment:string; tip:string };

const blankIngredient = ():IngredientDraft => ({section:'',name:'',quantity:'',unit:'',quantity_note:'',is_scalable:true,is_optional:false,is_pantry:false,preparation:'',substitutes:''});
const blankStep = ():StepDraft => ({title:'',instruction:'',timer_seconds:'',temperature:'',temperature_unit:'C',equipment:'',tip:''});
const numberOrNull = (value:unknown) => value === '' || value === null || value === undefined ? null : Number(value);
const tags = (value:string) => value.split(',').map(item=>item.trim()).filter(Boolean);
const input = 'min-h-11 w-full rounded-xl border border-[var(--color-border)] bg-black/10 px-3 text-sm text-white placeholder:text-[var(--color-text-secondary)]/70 focus:border-amber-400 focus:outline-none';
const label = 'text-xs font-medium text-[var(--color-text-secondary)]';

export default function RecipeEditor({spaceId, initial, onSaved, onCancel}:{spaceId:number;initial?:any;onSaved:(recipe:any)=>void;onCancel:()=>void}) {
    const [form,setForm]=useState({
        title:initial?.title??'',summary:initial?.summary??'',description:initial?.description??'',category:initial?.category??'main_course',cuisine:initial?.cuisine??'',difficulty:initial?.difficulty??'medium',status:initial?.status??'published',
        base_servings:initial?.base_servings??2,prep_minutes:initial?.prep_minutes??'',cook_minutes:initial?.cook_minutes??'',rest_minutes:initial?.rest_minutes??'',estimated_cost:initial?.estimated_cost??'',currency:initial?.currency??'CZK',
        calories_per_serving:initial?.nutrition?.calories??'',protein_per_serving:initial?.nutrition?.protein??'',carbs_per_serving:initial?.nutrition?.carbs??'',fat_per_serving:initial?.nutrition?.fat??'',
        dietary_tags:(initial?.dietary_tags??[]).join(', '),occasion_tags:(initial?.occasion_tags??[]).join(', '),equipment:(initial?.equipment??[]).join(', '),source_name:initial?.source_name??'',source_url:initial?.source_url??'',
        tips:initial?.tips??'',storage_notes:initial?.storage_notes??'',reheating_notes:initial?.reheating_notes??'',is_favorite:initial?.is_favorite??false,
    });
    const [ingredients,setIngredients]=useState<IngredientDraft[]>(initial?.ingredients?.map((item:any)=>({...blankIngredient(),...item,quantity:item.quantity??''}))??[blankIngredient()]);
    const [steps,setSteps]=useState<StepDraft[]>(initial?.steps?.map((item:any)=>({...blankStep(),...item,timer_seconds:item.timer_seconds??'',temperature:item.temperature??''}))??[blankStep()]);
    const [saving,setSaving]=useState(false); const [error,setError]=useState('');
    const total=useMemo(()=>Number(form.prep_minutes||0)+Number(form.cook_minutes||0)+Number(form.rest_minutes||0),[form.prep_minutes,form.cook_minutes,form.rest_minutes]);
    const set=(key:string,value:any)=>setForm(current=>({...current,[key]:value}));
    const updateIngredient=(index:number,key:keyof IngredientDraft,value:any)=>setIngredients(current=>current.map((item,i)=>i===index?{...item,[key]:value}:item));
    const updateStep=(index:number,key:keyof StepDraft,value:any)=>setSteps(current=>current.map((item,i)=>i===index?{...item,[key]:value}:item));
    const move=<T,>(items:T[],from:number,to:number)=>{if(to<0||to>=items.length)return items;const next=[...items];const [item]=next.splice(from,1);next.splice(to,0,item);return next;};
    const submit=async(event:FormEvent)=>{
        event.preventDefault();setSaving(true);setError('');
        const payload:any={...form,gallery_space_id:spaceId,base_servings:Number(form.base_servings),prep_minutes:Number(form.prep_minutes||0),cook_minutes:Number(form.cook_minutes||0),rest_minutes:Number(form.rest_minutes||0),estimated_cost:numberOrNull(form.estimated_cost),calories_per_serving:numberOrNull(form.calories_per_serving),protein_per_serving:numberOrNull(form.protein_per_serving),carbs_per_serving:numberOrNull(form.carbs_per_serving),fat_per_serving:numberOrNull(form.fat_per_serving),dietary_tags:tags(form.dietary_tags),occasion_tags:tags(form.occasion_tags),equipment:tags(form.equipment),cover_media_uuid:initial?.cover?.uuid??null,
            ingredients:ingredients.map(item=>({...item,quantity:numberOrNull(item.quantity)})),steps:steps.map(item=>({...item,timer_seconds:numberOrNull(item.timer_seconds),temperature:numberOrNull(item.temperature)}))};
        try{const response=initial?.uuid?await axios.put(`/api/v1/recipes/${initial.uuid}`,payload):await axios.post('/api/v1/recipes',payload);onSaved(response.data);}
        catch(reason:any){const errors=reason.response?.data?.errors;setError(errors?Object.values(errors).flat().join(' '):(reason.response?.data?.message??'Recept se nepodařilo uložit.'));}
        finally{setSaving(false);}
    };
    return <form onSubmit={submit} className="space-y-5">
        <div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-amber-300">{initial?'Úprava receptu':'Nový vlastní recept'}</p><h2 className="mt-1 text-xl font-semibold text-white">{initial?.title||'Co si spolu uvaříte?'}</h2></div><button type="button" onClick={onCancel} aria-label="Zavřít editor" className="rounded-lg border border-[var(--color-border)] p-2 text-[var(--color-text-secondary)] hover:text-white"><X size={18}/></button></div>
        {error&&<p className="rounded-xl border border-red-400/25 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
        <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><h3 className="font-semibold text-white">Základ receptu</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">
            <label className={`${label} sm:col-span-2`}>Název<input required value={form.title} onChange={e=>set('title',e.target.value)} className={`${input} mt-1`} placeholder="Např. naše krémové risotto"/></label>
            <label className={`${label} sm:col-span-2`}>Krátké představení<textarea value={form.summary} onChange={e=>set('summary',e.target.value)} rows={2} className={`${input} mt-1 py-3`} placeholder="Čím je recept výjimečný a kdy si ho dáváte?"/></label>
            <label className={label}>Kategorie<select value={form.category} onChange={e=>set('category',e.target.value)} className={`${input} mt-1`}><option value="breakfast">Snídaně</option><option value="soup">Polévka</option><option value="main_course">Hlavní jídlo</option><option value="side">Příloha</option><option value="salad">Salát</option><option value="dessert">Dezert</option><option value="baking">Pečení</option><option value="snack">Svačina</option><option value="drink">Nápoj</option><option value="sauce">Omáčka</option><option value="other">Ostatní</option></select></label>
            <label className={label}>Kuchyně<input value={form.cuisine} onChange={e=>set('cuisine',e.target.value)} className={`${input} mt-1`} placeholder="Česká, italská…"/></label>
            <label className={label}>Obtížnost<select value={form.difficulty} onChange={e=>set('difficulty',e.target.value)} className={`${input} mt-1`}><option value="easy">Snadné</option><option value="medium">Střední</option><option value="hard">Náročné</option></select></label>
            <label className={label}>Výchozí počet porcí<input required type="number" min="0.25" max="1000" step="0.25" value={form.base_servings} onChange={e=>set('base_servings',e.target.value)} className={`${input} mt-1`}/></label>
            <label className={`${label} sm:col-span-2`}>Podrobný popis<textarea value={form.description} onChange={e=>set('description',e.target.value)} rows={3} className={`${input} mt-1 py-3`} placeholder="Původ receptu, pro jakou příležitost se hodí…"/></label>
            <label className="flex items-center gap-2 text-sm text-amber-100"><input type="checkbox" checked={form.is_favorite} onChange={e=>set('is_favorite',e.target.checked)} className="h-4 w-4 accent-amber-500"/>Náš oblíbený recept</label>
            <label className={label}>Stav<select value={form.status} onChange={e=>set('status',e.target.value)} className={`${input} mt-1`}><option value="published">Sdílený recept</option><option value="draft">Rozepsaný koncept</option></select></label>
        </div></section>
        <section className="rounded-2xl border border-amber-400/20 bg-amber-500/5 p-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-white">Suroviny</h3><p className="mt-1 text-xs text-[var(--color-text-secondary)]">Číselná množství se automaticky přepočítají podle porcí. „Dle chuti“ nechte bez množství.</p></div><button type="button" onClick={()=>setIngredients(items=>[...items,blankIngredient()])} className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-amber-400/30 px-3 text-xs text-amber-100"><Plus size={14}/> Přidat</button></div>
            <div className="mt-4 space-y-3">{ingredients.map((item,index)=><div key={index} className="rounded-xl border border-[var(--color-border)] bg-black/10 p-3"><div className="grid gap-2 sm:grid-cols-12"><div className="hidden items-center justify-center sm:flex"><GripVertical size={16} className="text-[var(--color-text-secondary)]"/></div><input required value={item.name} onChange={e=>updateIngredient(index,'name',e.target.value)} className={`${input} sm:col-span-3`} placeholder="Surovina"/><input type="number" min="0" step="0.0001" value={item.quantity} onChange={e=>updateIngredient(index,'quantity',e.target.value)} className={`${input} sm:col-span-2`} placeholder="Množství"/><input value={item.unit} onChange={e=>updateIngredient(index,'unit',e.target.value)} className={`${input} sm:col-span-2`} placeholder="g, ml, ks…"/><input value={item.section} onChange={e=>updateIngredient(index,'section',e.target.value)} className={`${input} sm:col-span-2`} placeholder="Sekce"/><button type="button" disabled={ingredients.length===1} onClick={()=>setIngredients(items=>items.filter((_,i)=>i!==index))} className="min-h-10 rounded-lg text-red-300 disabled:opacity-30"><Trash2 className="mx-auto" size={16}/></button></div>
                <div className="mt-2 grid gap-2 sm:grid-cols-3"><input value={item.quantity_note} onChange={e=>updateIngredient(index,'quantity_note',e.target.value)} className={input} placeholder="Poznámka k množství"/><input value={item.preparation} onChange={e=>updateIngredient(index,'preparation',e.target.value)} className={input} placeholder="nakrájené najemno…"/><input value={item.substitutes} onChange={e=>updateIngredient(index,'substitutes',e.target.value)} className={input} placeholder="Možné náhrady"/></div><div className="mt-2 flex flex-wrap gap-4 text-xs text-[var(--color-text-secondary)]"><label><input type="checkbox" checked={item.is_scalable} onChange={e=>updateIngredient(index,'is_scalable',e.target.checked)} className="mr-1 accent-amber-500"/>Přepočítávat</label><label><input type="checkbox" checked={item.is_optional} onChange={e=>updateIngredient(index,'is_optional',e.target.checked)} className="mr-1 accent-amber-500"/>Volitelné</label><label><input type="checkbox" checked={item.is_pantry} onChange={e=>updateIngredient(index,'is_pantry',e.target.checked)} className="mr-1 accent-amber-500"/>Běžně ve spíži</label><button type="button" onClick={()=>setIngredients(items=>move(items,index,index-1))}>↑ výše</button><button type="button" onClick={()=>setIngredients(items=>move(items,index,index+1))}>↓ níže</button></div></div>)}</div>
        </section>
        <section className="rounded-2xl border border-orange-400/20 bg-orange-500/5 p-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-white">Postup a časovače</h3><p className="mt-1 text-xs text-[var(--color-text-secondary)]">Každý krok může mít vlastní teplotu, pomůcku, tip a spustitelný časovač.</p></div><button type="button" onClick={()=>setSteps(items=>[...items,blankStep()])} className="inline-flex min-h-10 items-center gap-1 rounded-lg border border-orange-400/30 px-3 text-xs text-orange-100"><Plus size={14}/> Krok</button></div>
            <div className="mt-4 space-y-3">{steps.map((item,index)=><div key={index} className="rounded-xl border border-[var(--color-border)] bg-black/10 p-3"><div className="flex items-center gap-2"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-orange-500 text-sm font-bold text-white">{index+1}</span><input value={item.title} onChange={e=>updateStep(index,'title',e.target.value)} className={input} placeholder="Název kroku"/><button type="button" disabled={steps.length===1} onClick={()=>setSteps(items=>items.filter((_,i)=>i!==index))} className="p-2 text-red-300 disabled:opacity-30"><Trash2 size={16}/></button></div><textarea required value={item.instruction} onChange={e=>updateStep(index,'instruction',e.target.value)} rows={3} className={`${input} mt-2 py-3`} placeholder="Popište přesně, co v tomto kroku udělat…"/><div className="mt-2 grid gap-2 sm:grid-cols-4"><label className={label}>Časovač (sekundy)<input type="number" min="0" value={item.timer_seconds} onChange={e=>updateStep(index,'timer_seconds',e.target.value)} className={`${input} mt-1`}/></label><label className={label}>Teplota<input type="number" value={item.temperature} onChange={e=>updateStep(index,'temperature',e.target.value)} className={`${input} mt-1`}/></label><label className={label}>Jednotka<select value={item.temperature_unit} onChange={e=>updateStep(index,'temperature_unit',e.target.value as 'C'|'F')} className={`${input} mt-1`}><option value="C">°C</option><option value="F">°F</option></select></label><label className={label}>Pomůcka<input value={item.equipment} onChange={e=>updateStep(index,'equipment',e.target.value)} className={`${input} mt-1`} placeholder="pánev…"/></label></div><input value={item.tip} onChange={e=>updateStep(index,'tip',e.target.value)} className={`${input} mt-2`} placeholder="Tip nebo častá chyba u tohoto kroku"/><div className="mt-2 flex gap-4 text-xs text-[var(--color-text-secondary)]"><button type="button" onClick={()=>setSteps(items=>move(items,index,index-1))}>↑ výše</button><button type="button" onClick={()=>setSteps(items=>move(items,index,index+1))}>↓ níže</button></div></div>)}</div>
        </section>
        <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><h3 className="font-semibold text-white">Čas, cena a výživa</h3><div className="mt-4 grid gap-3 sm:grid-cols-4"><label className={label}>Příprava (min)<input type="number" min="0" value={form.prep_minutes} onChange={e=>set('prep_minutes',e.target.value)} className={`${input} mt-1`}/></label><label className={label}>Vaření (min)<input type="number" min="0" value={form.cook_minutes} onChange={e=>set('cook_minutes',e.target.value)} className={`${input} mt-1`}/></label><label className={label}>Odpočinek (min)<input type="number" min="0" value={form.rest_minutes} onChange={e=>set('rest_minutes',e.target.value)} className={`${input} mt-1`}/></label><div className="rounded-xl bg-black/10 p-3 text-center"><p className="text-lg font-semibold text-white">{total} min</p><p className="text-[10px] text-[var(--color-text-secondary)]">celkem</p></div><label className={label}>Odhad ceny<input type="number" min="0" step="0.01" value={form.estimated_cost} onChange={e=>set('estimated_cost',e.target.value)} className={`${input} mt-1`}/></label><label className={label}>Měna<input maxLength={3} value={form.currency} onChange={e=>set('currency',e.target.value.toUpperCase())} className={`${input} mt-1`}/></label><label className={label}>kcal / porce<input type="number" min="0" value={form.calories_per_serving} onChange={e=>set('calories_per_serving',e.target.value)} className={`${input} mt-1`}/></label><label className={label}>Bílkoviny g / porce<input type="number" min="0" step="0.1" value={form.protein_per_serving} onChange={e=>set('protein_per_serving',e.target.value)} className={`${input} mt-1`}/></label><label className={label}>Sacharidy g / porce<input type="number" min="0" step="0.1" value={form.carbs_per_serving} onChange={e=>set('carbs_per_serving',e.target.value)} className={`${input} mt-1`}/></label><label className={label}>Tuky g / porce<input type="number" min="0" step="0.1" value={form.fat_per_serving} onChange={e=>set('fat_per_serving',e.target.value)} className={`${input} mt-1`}/></label></div></section>
        <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><h3 className="font-semibold text-white">Poznatky a metadata</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className={label}>Dietní označení oddělená čárkou<input value={form.dietary_tags} onChange={e=>set('dietary_tags',e.target.value)} className={`${input} mt-1`} placeholder="vegetariánské, bez lepku…"/></label><label className={label}>Příležitosti<input value={form.occasion_tags} onChange={e=>set('occasion_tags',e.target.value)} className={`${input} mt-1`} placeholder="rychlá večeře, výročí…"/></label><label className={`${label} sm:col-span-2`}>Potřebné vybavení<input value={form.equipment} onChange={e=>set('equipment',e.target.value)} className={`${input} mt-1`} placeholder="mixér, zapékací forma…"/></label><label className={label}>Zdroj / autor<input value={form.source_name} onChange={e=>set('source_name',e.target.value)} className={`${input} mt-1`}/></label><label className={label}>Odkaz na zdroj<input type="url" value={form.source_url} onChange={e=>set('source_url',e.target.value)} className={`${input} mt-1`} placeholder="https://"/></label><label className={`${label} sm:col-span-2`}>Osvědčené tipy<textarea value={form.tips} onChange={e=>set('tips',e.target.value)} rows={3} className={`${input} mt-1 py-3`}/></label><label className={label}>Uchovávání<textarea value={form.storage_notes} onChange={e=>set('storage_notes',e.target.value)} rows={3} className={`${input} mt-1 py-3`} placeholder="Jak dlouho vydrží…"/></label><label className={label}>Ohřev a servírování<textarea value={form.reheating_notes} onChange={e=>set('reheating_notes',e.target.value)} rows={3} className={`${input} mt-1 py-3`}/></label></div></section>
        <div className="sticky bottom-3 z-10 flex flex-col-reverse gap-2 rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-secondary)]/95 p-3 shadow-2xl backdrop-blur sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} className="min-h-11 rounded-xl border border-[var(--color-border)] px-5 text-sm text-white">Zrušit</button><button disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-amber-500 px-5 text-sm font-semibold text-black disabled:opacity-50"><Save size={17}/>{saving?'Ukládám…':initial?'Uložit změny':'Vytvořit recept'}</button></div>
    </form>;
}
