import AppLayout from '@/Layouts/AppLayout';
import PartnerDayNote from '@/Components/PartnerDayNote';
import { TodoPlanner } from '@/Components/TodoEntertainmentPlanner';
import { Head, Link } from '@inertiajs/react';
import axios from 'axios';
import { Check, Heart, ListPlus, Plus, Vote } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';

type Space = { id:number; name:string };
type Wishlist = { uuid:string; title:string; items:Array<{id:number;title:string;priority:number;season?:string;estimated_cost?:number;currency:string}> };
type Poll = { uuid:string; question:string; status:string; options:Array<{id:number;title:string;votes:number;calendar_event_id?:number|null}> };
type Template = { uuid:string; title:string; type:string; tasks?:string };

export default function PlanningIndex() {
    const [spaces,setSpaces]=useState<Space[]>([]); const [wishlists,setWishlists]=useState<Wishlist[]>([]); const [polls,setPolls]=useState<Poll[]>([]); const [templates,setTemplates]=useState<Template[]>([]); const [error,setError]=useState(''); const [notice,setNotice]=useState<{text:string;eventUuid?:string}>({text:''}); const [loading,setLoading]=useState(true);
    const [listTitle,setListTitle]=useState(''); const [item,setItem]=useState({title:'',priority:'3'}); const [poll,setPoll]=useState({question:'',first:'',second:''}); const [template,setTemplate]=useState({title:'',task:''});
    const load=async()=>{setLoading(true);setError('');const [calendar,lists,pollsData,templatesData]=await Promise.allSettled([axios.get('/api/v1/calendar/events'),axios.get('/api/v1/calendar/wishlists'),axios.get('/api/v1/calendar/polls'),axios.get('/api/v1/calendar/templates')]);if(calendar.status==='fulfilled')setSpaces(calendar.value.data.spaces??[]);if(lists.status==='fulfilled')setWishlists(lists.value.data??[]);if(pollsData.status==='fulfilled')setPolls(pollsData.value.data??[]);if(templatesData.status==='fulfilled')setTemplates(templatesData.value.data??[]);if(calendar.status==='rejected')setError('Kalendář se nepodařilo načíst. Zkontrolujte přihlášení a připojení, poté načítání opakujte.');else if([lists,pollsData,templatesData].some(result=>result.status==='rejected'))setError('Část plánovacích nástrojů se nepodařilo načíst. Ostatní plánování zůstává dostupné; po dokončení migrací zkuste načíst znovu.');setLoading(false);};
    useEffect(()=>{load();},[]);
    const firstSpace=spaces[0]?.id;
    const actionError=(reason:any)=>setError(reason?.response?.data?.message??'Změnu se nepodařilo uložit. Zkuste ji prosím znovu.');
    const addList=async(e:FormEvent)=>{e.preventDefault();if(!firstSpace||!listTitle.trim())return;try{await axios.post('/api/v1/calendar/wishlists',{gallery_space_id:firstSpace,title:listTitle});setListTitle('');await load();}catch(reason){actionError(reason);}};
    const addItem=async(e:FormEvent,list:Wishlist)=>{e.preventDefault();if(!item.title.trim())return;try{await axios.post(`/api/v1/calendar/wishlists/${list.uuid}/items`,{title:item.title,priority:Number(item.priority)});setItem({title:'',priority:'3'});await load();}catch(reason){actionError(reason);}};
    const addPoll=async(e:FormEvent)=>{e.preventDefault();if(!firstSpace||!poll.question||!poll.first||!poll.second)return;try{await axios.post('/api/v1/calendar/polls',{gallery_space_id:firstSpace,question:poll.question,options:[{title:poll.first},{title:poll.second}]});setPoll({question:'',first:'',second:''});await load();}catch(reason){actionError(reason);}};
    const vote=async(pollUuid:string,optionId:number)=>{try{await axios.post(`/api/v1/calendar/polls/${pollUuid}/vote`,{option_id:optionId});await load();}catch(reason){actionError(reason);}};
    const planPoll=async(poll:Poll,option:Poll['options'][number])=>{try{const response=await axios.post(`/api/v1/calendar/polls/${poll.uuid}/options/${option.id}/plan`);setNotice({text:`Rozhodnutí „${option.title}“ je v kalendáři jako společná akce.`,eventUuid:response.data.uuid});await load();}catch(reason){actionError(reason);}};
    const addTemplate=async(e:FormEvent)=>{e.preventDefault();if(!firstSpace||!template.title)return;try{await axios.post('/api/v1/calendar/templates',{gallery_space_id:firstSpace,title:template.title,tasks:template.task?[{title:template.task}]:[]});setTemplate({title:'',task:''});await load();}catch(reason){actionError(reason);}};
    const planWish=async(list:Wishlist,entry:Wishlist['items'][number])=>{try{const response=await axios.post(`/api/v1/calendar/wishlists/${list.uuid}/items/${entry.id}/plan`);setNotice({text:`„${entry.title}“ je naplánováno jako společná akce.`,eventUuid:response.data.uuid});await load();}catch(reason){actionError(reason);}};
    return <AppLayout><Head title="Společné plánování"/><main className="mx-auto max-w-6xl p-4 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h1 className="text-xl font-semibold text-white">Společné plánování</h1><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Nápady, rozhodnutí a opakovatelné přípravy — vždy v soukromém společném prostoru.</p></div><Link href="/calendar" className="text-sm text-[var(--color-accent)]">Kalendář a akce →</Link></div>{error&&<div className="mt-4 flex flex-wrap items-center gap-3 rounded-lg bg-red-500/10 p-3 text-sm text-red-200"><span>{error}</span><button onClick={load} disabled={loading} className="rounded border border-red-300/30 px-2 py-1 text-xs text-red-100 disabled:opacity-50">{loading?'Načítám…':'Načíst znovu'}</button></div>}{notice.text&&<div className="mt-4 rounded-lg bg-green-500/10 p-3 text-sm text-green-100">{notice.text}{notice.eventUuid&&<Link href={`/calendar/events/${notice.eventUuid}`} className="ml-2 underline">Otevřít v kalendáři</Link>}</div>}<div className="mt-5 grid gap-4 lg:grid-cols-3">
        <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><h2 className="flex items-center gap-2 font-semibold text-white"><Heart size={16} className="text-[var(--color-accent)]"/>Seznam přání</h2><form onSubmit={addList} className="mt-3 flex gap-2"><input value={listTitle} onChange={e=>setListTitle(e.target.value)} placeholder="Např. Výlety 2026" className="min-w-0 flex-1 rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-sm text-white"/><button className="rounded-lg bg-[var(--color-accent)] px-3"><Plus size={16}/></button></form><div className="mt-3 space-y-3">{wishlists.map(list=><div key={list.uuid} className="rounded-lg border border-[var(--color-border)] p-3"><p className="text-sm font-medium text-white">{list.title}</p><div className="mt-2 space-y-1">{list.items.map(entry=><div key={entry.id} className="flex items-center gap-2 rounded bg-black/10 px-2 py-1"><p className="min-w-0 flex-1 truncate text-xs text-[var(--color-text-secondary)]">{entry.title} <span className="text-[10px]">· priorita {entry.priority}</span></p><button type="button" onClick={()=>planWish(list,entry)} className="min-h-7 shrink-0 rounded border border-pink-400/30 px-2 text-[10px] text-pink-100">Do kalendáře</button></div>)}</div><form onSubmit={e=>addItem(e,list)} className="mt-2 flex gap-1"><input value={item.title} onChange={e=>setItem({...item,title:e.target.value})} placeholder="Přidat místo či zážitek" className="min-w-0 flex-1 rounded border border-[var(--color-border)] bg-black/10 px-2 py-1 text-xs text-white"/><button className="text-[var(--color-accent)]"><Plus size={15}/></button></form></div>)}{!wishlists.length&&<p className="text-sm text-[var(--color-text-secondary)]">Začněte společným nápadem na další volný víkend.</p>}</div></section>
        <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><h2 className="flex items-center gap-2 font-semibold text-white"><Vote size={16} className="text-[var(--color-accent)]"/>Rozhodnutí ve dvou</h2><form onSubmit={addPoll} className="mt-3 space-y-2"><input value={poll.question} onChange={e=>setPoll({...poll,question:e.target.value})} placeholder="Kam pojedeme o víkendu?" className="w-full rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-sm text-white"/><input value={poll.first} onChange={e=>setPoll({...poll,first:e.target.value})} placeholder="První možnost" className="w-full rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-sm text-white"/><input value={poll.second} onChange={e=>setPoll({...poll,second:e.target.value})} placeholder="Druhá možnost" className="w-full rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-sm text-white"/><button className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-sm text-white">Vytvořit hlasování</button></form><div className="mt-4 space-y-3">{polls.map(entry=><div key={entry.uuid} className="rounded-lg border border-[var(--color-border)] p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm text-white">{entry.question}</p>{entry.status === 'decided' && <span className="text-[10px] text-emerald-300">Rozhodnuto</span>}</div>{entry.options.map(option=><div key={option.id} className="mt-2 flex items-center gap-2 rounded border border-[var(--color-border)] px-2 py-1"><button disabled={entry.status !== 'open'} onClick={()=>vote(entry.uuid,option.id)} className="min-w-0 flex-1 truncate text-left text-xs text-[var(--color-text-secondary)] hover:text-white disabled:cursor-default">{option.title} <span>{option.votes} hlasů</span></button><button type="button" onClick={()=>planPoll(entry,option)} className="min-h-7 shrink-0 rounded border border-teal-400/30 px-2 text-[10px] text-teal-100">{option.calendar_event_id ? 'V kalendáři' : 'Naplánovat'}</button></div>)}</div>)}</div></section>
        <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><h2 className="flex items-center gap-2 font-semibold text-white"><ListPlus size={16} className="text-[var(--color-accent)]"/>Šablony příprav</h2><form onSubmit={addTemplate} className="mt-3 space-y-2"><input value={template.title} onChange={e=>setTemplate({...template,title:e.target.value})} placeholder="Např. Víkendová cesta" className="w-full rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-sm text-white"/><input value={template.task} onChange={e=>setTemplate({...template,task:e.target.value})} placeholder="První checklist úkol" className="w-full rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-sm text-white"/><button className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-sm text-white">Uložit šablonu</button></form><div className="mt-4 space-y-2">{templates.map(entry=><div key={entry.uuid} className="flex items-center gap-2 rounded-lg border border-[var(--color-border)] p-2 text-sm text-[var(--color-text-secondary)]"><Check size={14} className="text-[var(--color-accent)]"/>{entry.title}</div>)}{!templates.length&&<p className="text-sm text-[var(--color-text-secondary)]">Šablona uloží opakované přípravy a checklisty.</p>}</div><p className="mt-4 text-xs leading-relaxed text-[var(--color-text-secondary)]">Výjimky opakování, ICS export, nouzová karta a pravidla sdílení jsou dostupné u konkrétní akce nebo cesty; automatické sdílení nikdy neběží bez náhledu.</p></section>
    </div>{firstSpace && <div className="mt-5"><TodoPlanner spaceId={firstSpace}/></div>}<PartnerDayNote spaceId={firstSpace}/></main></AppLayout>;
}
