import AppLayout from '@/Layouts/AppLayout';
import { Head, Link, router } from '@inertiajs/react';
import axios from 'axios';
import { Lock, LockKeyhole, ShieldCheck, X } from 'lucide-react';
import { useState } from 'react';

interface VaultItem { id: number; uuid: string; original_filename: string; taken_at?: string; variants: Array<{ type: string; url: string }> }
export default function VaultIndex({ media }: { media: { data: VaultItem[]; total: number } }) {
    const [items, setItems] = useState(media.data);
    const remove = async (item: VaultItem) => { await axios.post(`/vault/media/${item.uuid}/toggle`); setItems(previous => previous.filter(value => value.id !== item.id)); };
    return <AppLayout><Head title="Soukromý trezor" /><div className="min-h-full pb-24"><header className="sticky top-0 z-20 border-b border-[var(--color-border)] bg-[var(--color-bg-primary)]/90 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[var(--color-accent)]/15"><LockKeyhole size={19} className="text-[var(--color-accent)]" /></div><div className="min-w-0 flex-1"><h1 className="font-semibold text-white">Soukromý trezor</h1><p className="text-xs text-[var(--color-text-secondary)]">{items.length} chráněných položek · automatické uzamčení za 15 minut</p></div><button onClick={() => router.post('/vault/lock')} className="flex min-h-11 items-center gap-2 rounded-xl border border-[var(--color-border)] px-3 text-xs text-white"><Lock size={14} /> Uzamknout</button></div></header><main className="mx-auto max-w-6xl p-3 sm:p-6">{items.length === 0 ? <div className="flex min-h-[60vh] flex-col items-center justify-center text-center"><ShieldCheck size={44} className="text-[var(--color-accent)]" /><h2 className="mt-4 text-lg font-semibold text-white">Trezor je prázdný</h2><p className="mt-2 max-w-sm text-sm text-[var(--color-text-secondary)]">U fotografie otevřete další akce a zvolte „Přesunout do trezoru“.</p></div> : <div className="grid grid-cols-3 gap-1 sm:grid-cols-4 sm:gap-2 lg:grid-cols-6">{items.map(item => { const thumb = item.variants.find(variant => variant.type === 'thumbnail')?.url; return <div key={item.id} className="group relative aspect-square overflow-hidden rounded-xl bg-[var(--color-bg-card)]"><Link href={`/media/${item.uuid}`} className="block h-full w-full">{thumb ? <img src={thumb} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center"><LockKeyhole /></div>}</Link><button onClick={() => remove(item)} title="Odebrat z trezoru" className="absolute right-1 top-1 flex h-9 w-9 items-center justify-center rounded-xl bg-black/65 text-white opacity-100 sm:opacity-0 sm:group-hover:opacity-100"><X size={14} /></button></div>; })}</div>}</main></div></AppLayout>;
}

