import BankConnectionManager from '@/Components/Banking/BankConnectionManager';
import { Link } from '@inertiajs/react';
import axios from 'axios';
import { ArrowDownRight, ArrowUpRight, ChevronDown, ChevronUp, CircleDollarSign, Link2, RefreshCw, ShieldCheck, WalletCards } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';

type BalancePoint={amount:number|null;method:string;as_of?:string|null;estimated:boolean};
type AccountBalance={account_uuid:string;name:string;currency:string;before:BalancePoint;after:BalancePoint;change:number|null};
type Transaction={link_id:number;uuid:string;status:'suggested'|'confirmed'|'excluded';confidence:number;reason?:string;timing:'before'|'during'|'after';direction:'debit'|'credit';amount:number;allocated_amount?:number|null;currency:string;booked_at:string;merchant:string;category:Category;is_internal_transfer:boolean;is_refund:boolean;is_fee:boolean;is_cash_withdrawal:boolean;account_name:string;activity?:{id:number;title:string}|null;place?:{id:number;name:string}|null};
type Category='transport'|'accommodation'|'food'|'activities'|'insurance'|'other';
type Snapshot={available:boolean;connected:boolean;balances:AccountBalance[];summary:{spent_by_currency:Record<string,number>;refunds_by_currency:Record<string,number>;fees_by_currency:Record<string,number>;cash_withdrawals:number;internal_transfers:number;suggested_count:number;confirmed_count:number;before_count:number;during_count:number;after_count:number};categories:Array<{category:Category;amounts:Record<string,number>;count:number}>;days:Array<{date:string;spent:number;refunds:number;currency:string}>;merchants:Array<{name:string;amount:number;currency:string;count:number}>;transactions:Transaction[]};

const CATEGORY:Record<Category,{label:string;color:string}>={transport:{label:'Doprava',color:'#38bdf8'},accommodation:{label:'Ubytování',color:'#a78bfa'},food:{label:'Jídlo a pití',color:'#f59e0b'},activities:{label:'Aktivity',color:'#ec4899'},insurance:{label:'Pojištění',color:'#34d399'},other:{label:'Ostatní',color:'#94a3b8'}};
const TIMING:Record<string,string>={before:'Před cestou',during:'Během cesty',after:'Po cestě'};
const empty:Snapshot={available:true,connected:false,balances:[],summary:{spent_by_currency:{},refunds_by_currency:{},fees_by_currency:{},cash_withdrawals:0,internal_transfers:0,suggested_count:0,confirmed_count:0,before_count:0,during_count:0,after_count:0},categories:[],days:[],merchants:[],transactions:[]};

export default function TripBankFinancePanel({tripId,gallerySpaceId,currency}:{tripId:number;gallerySpaceId:number;currency:string}){
    const [data,setData]=useState<Snapshot>(empty);const [loading,setLoading]=useState(true);const [open,setOpen]=useState(true);const [manager,setManager]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');
    const load=useCallback(async()=>{try{const response=await axios.get<Snapshot>(`/api/v1/trips/${tripId}/banking-finance`);setData(response.data);setError('');}catch(reason:any){setError(reason.response?.data?.message??'Bankovní výdaje se nepodařilo načíst.');}finally{setLoading(false);}},[tripId]);
    useEffect(()=>{load();},[load]);
    const patch=async(item:Transaction,values:Record<string,unknown>)=>{setBusy(String(item.link_id));setError('');try{const response=await axios.patch<Snapshot>(`/api/v1/trips/${tripId}/banking-finance/${item.link_id}`,values);setData(response.data);}catch(reason:any){setError(reason.response?.data?.message??'Přiřazení transakce se nepodařilo uložit.');}finally{setBusy('');}};
    const money=(amount:number,curr:string)=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:curr,maximumFractionDigits:2}).format(amount);
    const suggested=data.transactions.filter(item=>item.status==='suggested');
    const confirmed=data.transactions.filter(item=>item.status==='confirmed');
    const maxCategory=useMemo(()=>Math.max(1,...data.categories.flatMap(item=>Object.values(item.amounts))),[data.categories]);
    const maxDay=useMemo(()=>Math.max(1,...data.days.map(item=>item.spent)),[data.days]);
    const mainSpent=Number(data.summary?.spent_by_currency?.[currency]??0);

    if(loading)return <section className="mb-5 flex min-h-24 items-center justify-center rounded-3xl border border-[var(--color-border)] bg-[var(--color-bg-card)]"><RefreshCw size={18} className="animate-spin text-[var(--color-accent)]"/></section>;
    if(!data.available)return <section className="mb-5 rounded-2xl border border-amber-400/20 bg-amber-500/10 p-4 text-xs text-amber-100">Finanční historie se zpřístupní po dokončení databázových migrací.</section>;
    if(!data.connected)return <div className="mb-5"><BankConnectionManager gallerySpaceId={gallerySpaceId} returnTripId={tripId} compact onChanged={load}/></div>;

    return <section id="bank-finance" className="mb-5 scroll-mt-24 overflow-hidden rounded-3xl border border-emerald-400/20 bg-gradient-to-br from-emerald-500/10 via-[var(--color-bg-card)] to-[var(--color-bg-card)]">
        <button onClick={()=>setOpen(value=>!value)} className="flex min-h-16 w-full items-center gap-3 p-4 text-left sm:p-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-emerald-500/15 text-emerald-300"><WalletCards size={20}/></div><div className="min-w-0 flex-1"><p className="text-[10px] font-medium uppercase tracking-wider text-emerald-200">Skutečné finance cesty</p><h2 className="truncate text-base font-semibold text-white">Revolut · automatická historie a párování</h2></div><div className="hidden text-right sm:block"><p className="text-lg font-semibold text-white">{money(mainSpent,currency)}</p><p className="text-[10px] text-[var(--color-text-secondary)]">potvrzené výdaje · {data.summary.confirmed_count} transakcí</p></div>{open?<ChevronUp size={18} className="text-[var(--color-text-secondary)]"/>:<ChevronDown size={18} className="text-[var(--color-text-secondary)]"/>}</button>
        {open&&<div className="border-t border-white/10 p-3 sm:p-5">
            {error&&<p className="mb-3 rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-xs text-red-100">{error}</p>}
            <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.balances.map(account=><article key={account.account_uuid} className="rounded-2xl border border-white/10 bg-black/10 p-3"><p className="truncate text-xs font-medium text-white">{account.name}</p><div className="mt-3 grid grid-cols-2 gap-2"><Balance label="Před cestou" point={account.before} currency={account.currency}/><Balance label="Po cestě" point={account.after} currency={account.currency}/></div>{account.change!==null&&<p className={`mt-2 text-xs ${account.change<0?'text-amber-200':'text-emerald-200'}`}>Rozdíl {money(account.change,account.currency)}</p>}</article>)}</div>
            <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={CircleDollarSign} label="Utraceno" values={data.summary.spent_by_currency} tone="text-amber-200"/><Metric icon={ArrowUpRight} label="Vráceno" values={data.summary.refunds_by_currency} tone="text-emerald-200"/><div className="rounded-2xl bg-black/10 p-3"><p className="text-[10px] text-[var(--color-text-secondary)]">Přiřazení podle období</p><p className="mt-1 text-sm text-white">{data.summary.before_count} před · {data.summary.during_count} během · {data.summary.after_count} po</p></div><div className="rounded-2xl bg-black/10 p-3"><p className="text-[10px] text-[var(--color-text-secondary)]">Neutrální pohyby</p><p className="mt-1 text-sm text-white">{data.summary.internal_transfers} převodů · {data.summary.cash_withdrawals} výběrů</p></div></div>
            {(data.categories.length>0||data.days.length>0)&&<div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-black/10 p-3"><p className="text-xs font-medium text-white">Za co jsme utráceli</p><div className="mt-3 space-y-2">{data.categories.map(item=>{const amount=Number(item.amounts[currency]??Object.values(item.amounts)[0]??0);const curr=item.amounts[currency]!==undefined?currency:Object.keys(item.amounts)[0]??currency;return <div key={item.category}><div className="flex justify-between gap-2 text-[11px]"><span className="text-[var(--color-text-secondary)]">{CATEGORY[item.category]?.label??item.category} · {item.count}×</span><span className="text-white">{money(amount,curr)}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full" style={{width:`${Math.max(3,Math.round(amount/maxCategory*100))}%`,backgroundColor:CATEGORY[item.category]?.color}}/></div></div>})}</div></div><div className="rounded-2xl border border-white/10 bg-black/10 p-3"><p className="text-xs font-medium text-white">Průběh výdajů po dnech</p><div className="mt-3 flex h-28 items-end gap-1.5 overflow-x-auto pb-5">{data.days.map(day=><div key={`${day.date}-${day.currency}`} title={`${day.date}: ${money(day.spent,day.currency)}`} className="relative flex h-full min-w-7 flex-1 items-end"><div className="w-full rounded-t bg-emerald-400/70" style={{height:`${Math.max(4,Math.round(day.spent/maxDay*100))}%`}}/><span className="absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap text-[8px] text-[var(--color-text-secondary)]">{new Date(`${day.date}T12:00:00`).toLocaleDateString('cs-CZ',{day:'numeric',month:'numeric'})} · {day.currency}</span></div>)}</div></div></div>}
            {suggested.length>0&&<div className="mt-4 rounded-2xl border border-amber-400/20 bg-amber-500/5 p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-xs font-medium text-amber-100">Zkontrolovat navržené platby</p><p className="mt-0.5 text-[10px] text-amber-100/70">Nejisté platby se do skutečného rozpočtu nezapočítají bez vašeho potvrzení.</p></div><span className="rounded-full bg-amber-500/15 px-2 py-1 text-xs text-amber-100">{suggested.length}</span></div><div className="mt-2 space-y-2">{suggested.map(item=><TransactionRow key={item.link_id} item={item} busy={busy===String(item.link_id)} onPatch={values=>patch(item,values)}/>)}</div></div>}
            {confirmed.length>0&&<details className="mt-4 rounded-2xl border border-white/10 bg-black/10"><summary className="cursor-pointer list-none p-3 text-xs font-medium text-white">Spárovaná historie ({confirmed.length})</summary><div className="space-y-2 border-t border-white/5 p-3">{confirmed.map(item=><TransactionRow key={item.link_id} item={item} busy={busy===String(item.link_id)} onPatch={values=>patch(item,values)}/>)}</div></details>}
            {data.merchants.length>0&&<div className="mt-4 flex flex-wrap gap-2">{data.merchants.map(item=><span key={`${item.name}-${item.currency}`} className="rounded-full border border-white/10 bg-black/10 px-3 py-1.5 text-[10px] text-[var(--color-text-secondary)]">{item.name} · <strong className="text-white">{money(item.amount,item.currency)}</strong> · {item.count}×</span>)}</div>}
            <div className="mt-4 flex flex-col gap-2 border-t border-white/10 pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-start gap-2 text-[10px] leading-relaxed text-[var(--color-text-secondary)]"><ShieldCheck size={14} className="shrink-0 text-emerald-300"/>Původní historie zůstává v databázi. Ruční potvrzení a kategorie automatická synchronizace nepřepíše.</p><button onClick={()=>setManager(value=>!value)} className="min-h-9 rounded-lg border border-white/10 px-3 text-xs text-emerald-100">{manager?'Skrýt správu':'Synchronizace a výpisy'}</button></div>
            {manager&&<div className="mt-3"><BankConnectionManager gallerySpaceId={gallerySpaceId} returnTripId={tripId} compact onChanged={load}/></div>}
            <Link href="/finances" className="mt-3 inline-flex text-xs text-emerald-200 hover:text-white">Otevřít celkové finance, transakce a grafy →</Link>
        </div>}
    </section>;
}

function Balance({label,point,currency}:{label:string;point:BalancePoint;currency:string}){const text=point.amount===null?'Nedostupné':new Intl.NumberFormat('cs-CZ',{style:'currency',currency,maximumFractionDigits:2}).format(point.amount);return <div><p className="text-[9px] text-[var(--color-text-secondary)]">{label}</p><p className="mt-0.5 text-sm font-semibold text-white">{text}</p>{point.estimated&&point.amount!==null&&<p className="mt-0.5 text-[8px] text-amber-200">rekonstruovaný odhad</p>}</div>}
function Metric({icon:Icon,label,values,tone}:{icon:any;label:string;values:Record<string,number>;tone:string}){const entries=Object.entries(values??{});return <div className="rounded-2xl bg-black/10 p-3"><p className="flex items-center gap-1 text-[10px] text-[var(--color-text-secondary)]"><Icon size={12}/>{label}</p><p className={`mt-1 text-sm font-semibold ${tone}`}>{entries.length?entries.map(([currency,amount])=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency,maximumFractionDigits:2}).format(amount)).join(' · '):'—'}</p></div>}
function TransactionRow({item,busy,onPatch}:{item:Transaction;busy:boolean;onPatch:(values:Record<string,unknown>)=>void}){
    const category=CATEGORY[item.category]??CATEGORY.other;
    const original=Math.abs(item.amount); const current=item.allocated_amount??original;
    const [allocation,setAllocation]=useState(String(current));
    useEffect(()=>setAllocation(String(item.allocated_amount??Math.abs(item.amount))),[item.allocated_amount,item.amount]);
    const parsed=Math.max(0,Math.min(original,Number(allocation)||0));
    const changed=Math.abs(parsed-current)>0.0001;
    return <article className="rounded-xl border border-white/10 bg-[var(--color-bg-card)] p-3">
        <div className="flex items-start gap-2"><div className={`mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg ${item.direction==='credit'?'bg-emerald-500/10 text-emerald-300':'bg-amber-500/10 text-amber-200'}`}>{item.direction==='credit'?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>}</div><div className="min-w-0 flex-1"><div className="flex flex-col gap-1 sm:flex-row sm:items-start sm:justify-between"><div><p className="truncate text-xs font-medium text-white">{item.merchant}</p><p className="mt-0.5 text-[9px] text-[var(--color-text-secondary)]">{new Date(item.booked_at).toLocaleString('cs-CZ')} · {TIMING[item.timing]} · {item.account_name}</p></div><p className={`shrink-0 text-sm font-semibold ${item.direction==='credit'?'text-emerald-200':'text-white'}`}>{new Intl.NumberFormat('cs-CZ',{style:'currency',currency:item.currency,maximumFractionDigits:2}).format(current)}</p></div><div className="mt-2 flex flex-wrap items-center gap-2"><select value={item.category} disabled={busy} onChange={event=>onPatch({category:event.target.value})} className="min-h-8 rounded-lg border border-white/10 bg-[var(--color-bg-primary)] px-2 text-[10px] text-white" style={{borderColor:`${category.color}55`}}>{Object.entries(CATEGORY).map(([value,meta])=><option key={value} value={value}>{meta.label}</option>)}</select><span className="text-[9px] text-[var(--color-text-secondary)]">shoda {Math.round(item.confidence*100)} %</span>{item.activity&&<span className="inline-flex items-center gap-1 text-[9px] text-sky-200"><Link2 size={9}/>{item.activity.title}</span>}{item.place&&<span className="inline-flex items-center gap-1 text-[9px] text-pink-200"><Link2 size={9}/>{item.place.name}</span>}{item.is_internal_transfer&&<span className="text-[9px] text-violet-200">vlastní převod</span>}{item.is_refund&&<span className="text-[9px] text-emerald-200">vratka</span>}</div>{item.reason&&<p className="mt-1 text-[9px] text-[var(--color-text-secondary)]">{item.reason}</p>}</div></div>
        <div className="mt-2 flex flex-wrap items-center gap-2 border-t border-white/5 pt-2"><label className="flex items-center gap-1 text-[9px] text-[var(--color-text-secondary)]">Část pro tuto cestu<input type="number" min="0" max={original} step="0.01" value={allocation} onChange={event=>setAllocation(event.target.value)} className="h-8 w-24 rounded-lg border border-white/10 bg-[var(--color-bg-primary)] px-2 text-[10px] text-white"/> {item.currency}</label>{item.status==='suggested'&&<><button disabled={busy} onClick={()=>onPatch({status:'confirmed',allocated_amount:parsed})} className="min-h-8 flex-1 rounded-lg bg-emerald-500 px-3 text-[10px] font-medium text-white disabled:opacity-50">Patří k cestě</button><button disabled={busy} onClick={()=>onPatch({status:'excluded'})} className="min-h-8 rounded-lg border border-white/10 px-3 text-[10px] text-[var(--color-text-secondary)] disabled:opacity-50">Nesouvisí</button></>}{item.status==='confirmed'&&<><button disabled={busy||!changed} onClick={()=>onPatch({allocated_amount:parsed})} className="min-h-8 rounded-lg border border-emerald-300/20 px-3 text-[10px] text-emerald-100 disabled:opacity-40">Uložit část</button><button disabled={busy} onClick={()=>onPatch({status:'excluded'})} className="min-h-8 rounded-lg px-2 text-[9px] text-[var(--color-text-secondary)] hover:text-red-200">Vyřadit</button></>}</div>
    </article>;
}
