import AppLayout from '@/Layouts/AppLayout';
import { Head, Link } from '@inertiajs/react';
import axios from 'axios';
import { Heart, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';

type Moment = { uuid:string; title:string; note?:string|null; happened_on?:string|null; is_favorite:boolean; media:{uuid:string;title:string;thumbnail_url?:string|null}[] };

export default function SharedMemoriesIndex() {
    const [items, setItems] = useState<Moment[]>([]);
    const [loading, setLoading] = useState(true);
    const load = () => axios.get('/api/v1/shared-memory-moments').then(response => setItems(response.data ?? [])).finally(() => setLoading(false));
    useEffect(() => { load(); }, []);
    const remove = async (item:Moment) => { if (!confirm(`Smazat „${item.title}“?`)) return; await axios.delete(`/api/v1/shared-memory-moments/${item.uuid}`); setItems(current => current.filter(entry => entry.uuid !== item.uuid)); };
    return <AppLayout><Head title="Naše vzpomínky"/><main className="mx-auto max-w-5xl p-4 pb-24 sm:p-6"><header className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-[var(--color-text-secondary)]">Společný archiv</p><h1 className="text-2xl font-bold text-white">Naše vybrané vzpomínky</h1><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Zastavte se u momentů, které jste si vybrali společně.</p></div><Link href="/memories" className="text-sm text-[var(--color-accent)]">Objevit další →</Link></header>{loading ? <div className="grid gap-4 sm:grid-cols-2">{[1,2].map(item => <div key={item} className="h-64 animate-pulse rounded-3xl bg-[var(--color-bg-card)]"/>)}</div> : !items.length ? <section className="rounded-3xl border border-dashed border-[var(--color-border)] p-10 text-center"><Heart className="mx-auto text-[var(--color-accent)]" size={32}/><h2 className="mt-3 font-semibold text-white">Zatím žádný společný výběr</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Na stránce Vzpomínky otevřete výběr a uložte jej tlačítkem „Pro nás“.</p></section> : <div className="grid gap-4 sm:grid-cols-2">{items.map(item => <article key={item.uuid} className="overflow-hidden rounded-3xl border border-[var(--color-border)] bg-[var(--color-bg-card)]"><div className="grid h-40 grid-cols-3 gap-1 bg-[var(--color-bg-secondary)]">{item.media.slice(0,3).map(media => <Link key={media.uuid} href={`/media/${media.uuid}`} className="overflow-hidden">{media.thumbnail_url ? <img src={media.thumbnail_url} alt="" className="h-full w-full object-cover"/> : <div className="h-full bg-[var(--color-accent)]/20"/>}</Link>)}{!item.media.length&&<div className="col-span-3 flex items-center justify-center text-4xl">💞</div>}</div><div className="p-4"><div className="flex gap-3"><div className="min-w-0 flex-1"><h2 className="truncate font-semibold text-white">{item.is_favorite && '♥ '}{item.title}</h2>{item.happened_on&&<p className="mt-1 text-xs text-[var(--color-text-secondary)]">{new Date(`${item.happened_on}T12:00:00`).toLocaleDateString('cs-CZ')}</p>}{item.note&&<p className="mt-3 text-sm text-[var(--color-text-secondary)]">{item.note}</p>}</div><button onClick={() => remove(item)} className="p-2 text-[var(--color-text-secondary)] hover:text-red-300" aria-label="Smazat vzpomínku"><Trash2 size={16}/></button></div></div></article>)}</div>}</main></AppLayout>;
}
