import RecipeEditor from '@/Components/Recipes/RecipeEditor';
import AppLayout from '@/Layouts/AppLayout';
import { Head, Link } from '@inertiajs/react';
import axios from 'axios';
import { ChefHat, Clock3, Heart, Plus, Search, Star, Utensils } from 'lucide-react';
import { useEffect, useState } from 'react';

const categories:Record<string,string>={breakfast:'Snídaně',soup:'Polévka',main_course:'Hlavní jídlo',side:'Příloha',salad:'Salát',dessert:'Dezert',baking:'Pečení',snack:'Svačina',drink:'Nápoj',sauce:'Omáčka',other:'Ostatní'};
const difficulties:Record<string,string>={easy:'Snadné',medium:'Střední',hard:'Náročné'};

export default function RecipesIndex(){
    const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [editing,setEditing]=useState(false);
    const [filters,setFilters]=useState({q:'',category:'',difficulty:'',favorite:false,sort:'newest'});
    const load=async()=>{setLoading(true);setError('');try{const response=await axios.get('/api/v1/recipes',{params:{...filters,favorite:filters.favorite?1:undefined}});setData(response.data);}catch(reason:any){setError(reason.response?.status===503?'Recepty vyžadují dokončení databázových migrací.':reason.response?.data?.message??'Kuchařku se nepodařilo načíst.');}finally{setLoading(false);}};
    useEffect(()=>{const timer=setTimeout(load,filters.q?300:0);return()=>clearTimeout(timer);},[filters.q,filters.category,filters.difficulty,filters.favorite,filters.sort]);
    if(editing)return <AppLayout><Head title="Nový recept"/><main className="mx-auto max-w-6xl p-4 pb-24 sm:p-6"><RecipeEditor spaceId={data?.gallery_space_id} onSaved={recipe=>{window.location.href=`/recipes/${recipe.uuid}`;}} onCancel={()=>setEditing(false)}/></main></AppLayout>;
    return <AppLayout><Head title="Naše kuchařka"/><main className="mx-auto max-w-7xl p-4 pb-24 sm:p-6">
        <header className="overflow-hidden rounded-3xl border border-amber-400/20 bg-gradient-to-br from-amber-500/15 via-orange-500/5 to-[var(--color-bg-card)] p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-xs font-medium uppercase tracking-[.22em] text-amber-300"><ChefHat size={16}/>Naše společná kuchařka</p><h1 className="mt-2 text-3xl font-semibold text-white">Vaříme, ochutnáváme, zlepšujeme</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[var(--color-text-secondary)]">Vlastní recepty s přesným přepočtem porcí, společným plánováním a historií každého vaření. Poznatky už se neztratí mezi zprávami ani fotografiemi.</p></div><button onClick={()=>setEditing(true)} disabled={!data?.gallery_space_id} className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-amber-500 px-5 font-semibold text-black shadow-lg shadow-amber-500/10 disabled:opacity-40"><Plus size={19}/>Nový recept</button></div>
            <div className="mt-6 grid grid-cols-3 gap-2 sm:max-w-xl"><div className="rounded-xl bg-black/10 p-3 text-center"><p className="text-xl font-semibold text-white">{data?.summary?.recipes??0}</p><p className="text-[10px] text-[var(--color-text-secondary)]">receptů</p></div><div className="rounded-xl bg-black/10 p-3 text-center"><p className="text-xl font-semibold text-amber-200">{data?.summary?.favorites??0}</p><p className="text-[10px] text-[var(--color-text-secondary)]">oblíbených</p></div><div className="rounded-xl bg-black/10 p-3 text-center"><p className="text-xl font-semibold text-orange-200">{data?.summary?.cookings??0}</p><p className="text-[10px] text-[var(--color-text-secondary)]">společných vaření</p></div></div>
        </header>
        <section className="mt-5 rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-3"><div className="grid gap-2 md:grid-cols-[minmax(220px,1fr)_repeat(3,minmax(140px,auto))_auto]"><label className="relative"><Search size={16} className="absolute left-3 top-3 text-[var(--color-text-secondary)]"/><input value={filters.q} onChange={e=>setFilters(current=>({...current,q:e.target.value}))} className="min-h-10 w-full rounded-xl border border-[var(--color-border)] bg-black/10 pl-9 pr-3 text-sm text-white" placeholder="Název, kuchyně nebo surovina…"/></label><select value={filters.category} onChange={e=>setFilters(current=>({...current,category:e.target.value}))} className="min-h-10 rounded-xl border border-[var(--color-border)] bg-black/10 px-3 text-sm text-white"><option value="">Všechny kategorie</option>{Object.entries(categories).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select><select value={filters.difficulty} onChange={e=>setFilters(current=>({...current,difficulty:e.target.value}))} className="min-h-10 rounded-xl border border-[var(--color-border)] bg-black/10 px-3 text-sm text-white"><option value="">Každá obtížnost</option>{Object.entries(difficulties).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select><select value={filters.sort} onChange={e=>setFilters(current=>({...current,sort:e.target.value}))} className="min-h-10 rounded-xl border border-[var(--color-border)] bg-black/10 px-3 text-sm text-white"><option value="newest">Nejnovější</option><option value="title">Podle názvu</option><option value="rating">Nejlépe hodnocené</option><option value="cooked">Naposledy vařené</option></select><button onClick={()=>setFilters(current=>({...current,favorite:!current.favorite}))} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-3 text-sm ${filters.favorite?'bg-amber-500 text-black':'border border-[var(--color-border)] text-[var(--color-text-secondary)]'}`}><Heart size={15} fill={filters.favorite?'currentColor':'none'}/>Oblíbené</button></div></section>
        {error&&<p className="mt-5 rounded-xl border border-red-400/25 bg-red-500/10 p-4 text-sm text-red-200">{error}</p>}
        {loading?<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5,6].map(item=><div key={item} className="h-72 animate-pulse rounded-2xl bg-white/5"/>)}</div>:data?.items?.length?<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.items.map((recipe:any)=><Link key={recipe.uuid} href={`/recipes/${recipe.uuid}`} className="group overflow-hidden rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] transition hover:-translate-y-0.5 hover:border-amber-400/35 hover:shadow-xl">
            <div className="relative aspect-[16/10] overflow-hidden bg-gradient-to-br from-amber-500/20 to-orange-700/10">{recipe.cover?.thumbnail_url?<img src={recipe.cover.thumbnail_url} loading="lazy" alt={recipe.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]"/>:<div className="flex h-full items-center justify-center"><ChefHat size={52} className="text-amber-300/50"/></div>}<div className="absolute inset-x-0 bottom-0 h-20 bg-gradient-to-t from-black/70 to-transparent"/>{recipe.is_favorite&&<span className="absolute right-3 top-3 rounded-full bg-black/60 p-2 text-amber-300"><Heart size={16} fill="currentColor"/></span>}<span className="absolute bottom-3 left-3 rounded-full bg-black/55 px-2.5 py-1 text-[10px] text-white backdrop-blur">{categories[recipe.category]??recipe.category}</span></div>
            <div className="p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-white group-hover:text-amber-100">{recipe.title}</h2><p className="mt-1 line-clamp-2 text-xs leading-relaxed text-[var(--color-text-secondary)]">{recipe.summary||'Vlastní recept připravený pro vaše společné vaření.'}</p></div>{recipe.stats.average_rating&&<span className="inline-flex shrink-0 items-center gap-1 text-xs text-amber-200"><Star size={13} fill="currentColor"/>{Number(recipe.stats.average_rating).toLocaleString('cs-CZ')}</span>}</div><div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-[var(--color-text-secondary)]"><span className="inline-flex items-center gap-1"><Clock3 size={13}/>{recipe.total_minutes} min</span><span className="inline-flex items-center gap-1"><Utensils size={13}/>{recipe.base_servings} porce</span><span>{difficulties[recipe.difficulty]??recipe.difficulty}</span>{recipe.stats.times_cooked>0&&<span>Vařeno {recipe.stats.times_cooked}×</span>}</div></div>
        </Link>)}</div>:!error&&<div className="mt-8 rounded-3xl border border-dashed border-amber-400/30 bg-amber-500/5 p-10 text-center"><ChefHat size={44} className="mx-auto text-amber-300"/><h2 className="mt-3 text-lg font-semibold text-white">Začněte prvním společným receptem</h2><p className="mx-auto mt-2 max-w-lg text-sm text-[var(--color-text-secondary)]">Zapište rodinný recept, vlastní oblíbené jídlo nebo výsledek společného experimentu. Systém pak pohlídá porce, postup i historii zlepšení.</p><button onClick={()=>setEditing(true)} className="mt-5 rounded-xl bg-amber-500 px-5 py-3 font-semibold text-black">Vytvořit první recept</button></div>}
    </main></AppLayout>;
}
