import { Link } from '@inertiajs/react';
import axios from 'axios';
import { Check, Clock, Heart, MapPin, Route, Save, Sparkles, Wallet } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';

type DateReaction = { user_id:number; user_name?:string; reaction:'love'|'maybe'|'pass'; rating?:number|null; note?:string|null; is_mine?:boolean };
type DateBlock = { key:string; title:string; description:string; icon:string; minutes:number; estimated_cost:number };
export interface DateExperience {
    uuid:string; title:string; summary:string; theme:string; status:string; estimated_cost:number; currency:string; estimated_minutes:number;
    novelty_percent:number; travel_scope:string; transport_mode:string; destination?:{location_name?:string}|null;
    plan:{blocks:DateBlock[];reasons?:string[];rain_backup?:string;memory_prompt?:string;budget?:{activities:number;transport:number;total:number;limit:number;currency:string;is_estimate:boolean};weather?:{precipitation_probability?:number;temperature_min?:number;temperature_max?:number;unavailable?:boolean};trip_sync?:{status:'synced'|'migration_required';trip_id:number;activities:number;expenses:number;routes:number;waypoints:number;packing_items:number;message?:string;created?:Record<string,number>}};
    reactions:DateReaction[]; my_reaction?:'love'|'maybe'|'pass'|null; my_rating?:number|null; my_note?:string|null;
    feedback:{rated_count:number;participant_count:number;average_rating?:number|null;complete:boolean};
}
type Experience = {attached_media_count:number;reflection_exists:boolean;memory?:{uuid:string;title:string}|null};

export default function DateExperiencePanel({ idea, isFuture, experience, onChanged }:{idea:DateExperience;eventUuid:string;isFuture:boolean;experience:Experience;onChanged:()=>void}) {
    const [rating,setRating]=useState(Number(idea.my_rating??0)); const [reaction,setReaction]=useState<'love'|'maybe'|'pass'>(idea.my_reaction??'love');
    const [note,setNote]=useState(idea.my_note??''); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
    useEffect(()=>{setRating(Number(idea.my_rating??0));setReaction(idea.my_reaction??'love');setNote(idea.my_note??'');},[idea.uuid,idea.my_rating,idea.my_reaction,idea.my_note]);
    const save=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setMessage('');try{await axios.patch(`/api/v1/date-ideas/${idea.uuid}/reaction`,{reaction,rating:rating||null,note:note||null});setMessage('Váš pohled je uložený a další návrhy se mu přizpůsobí.');onChanged();}catch(error:any){setMessage(error?.response?.data?.message??'Hodnocení se nepodařilo uložit.');}finally{setSaving(false);}};
    const steps=[
        {label:'Program připraven',done:true}, {label:'Randíčko proběhlo',done:!isFuture},
        {label:'Můj dojem',done:Boolean(idea.my_rating)}, {label:'Fotografie',done:experience.attached_media_count>0},
        {label:'Společná vzpomínka',done:Boolean(experience.memory)},
    ];
    return <section className="mt-5 overflow-hidden rounded-3xl border border-pink-400/25 bg-gradient-to-br from-pink-500/10 via-[var(--color-bg-card)] to-violet-500/10">
        <div className="p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-medium uppercase tracking-wider text-pink-200">Vygenerované randíčko · {idea.novelty_percent}% nové</p><h2 className="mt-1 flex items-center gap-2 text-lg font-semibold text-white"><Sparkles size={18} className="text-pink-300"/>Program zůstává součástí této akce</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">{idea.summary}</p></div><Link href="/date-ideas" className="shrink-0 text-xs text-pink-200 hover:text-white">Historie a další nápady →</Link></div>
            <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric icon={Wallet} value={`${money(idea.estimated_cost)} ${idea.currency}`} label="odhad pro dva"/><Metric icon={Clock} value={duration(idea.estimated_minutes)} label="délka programu"/><Metric icon={Route} value={scope(idea.travel_scope)} label={transport(idea.transport_mode)}/><Metric icon={MapPin} value={idea.destination?.location_name||'flexibilní'} label="lokalita"/></div>
            <div className="mt-4 grid gap-2 md:grid-cols-2">{idea.plan.blocks.map((block,index)=><div key={block.key} className="grid grid-cols-[32px_minmax(0,1fr)_auto] gap-2 rounded-xl border border-pink-300/15 bg-black/10 p-3"><span className="text-xl">{block.icon}</span><div><p className="text-sm font-medium text-white">{index+1}. {block.title}</p><p className="mt-1 text-[11px] leading-relaxed text-[var(--color-text-secondary)]">{block.description}</p></div><span className="text-[10px] text-[var(--color-text-secondary)]">{block.minutes} min</span></div>)}</div>
            <details className="mt-3 rounded-xl border border-[var(--color-border)] bg-black/10 p-3"><summary className="cursor-pointer text-xs font-medium text-pink-100">Rozpočet, počasí a záložní varianta</summary><div className="mt-2 space-y-2 text-[11px] text-[var(--color-text-secondary)]">{idea.plan.budget&&<p>Aktivity {money(idea.plan.budget.activities)} + doprava {money(idea.plan.budget.transport)} = <strong className="text-white">{money(idea.plan.budget.total)} {idea.currency}</strong>. Jde o odhad, nikoli živou cenu.</p>}{idea.plan.weather&&!idea.plan.weather.unavailable&&<p>Počasí: {idea.plan.weather.temperature_min}–{idea.plan.weather.temperature_max} °C · pravděpodobnost deště {idea.plan.weather.precipitation_probability}%.</p>}{idea.plan.rain_backup&&<p><strong className="text-white">Mokrá varianta:</strong> {idea.plan.rain_backup}</p>}{idea.plan.memory_prompt&&<p><strong className="text-white">Vzpomínka dne:</strong> {idea.plan.memory_prompt}</p>}</div></details>
            {idea.plan.trip_sync&&<div className={`mt-3 flex flex-col gap-2 rounded-xl border p-3 text-xs sm:flex-row sm:items-center ${idea.plan.trip_sync.status==='synced'?'border-emerald-400/25 bg-emerald-500/10 text-emerald-100':'border-amber-400/25 bg-amber-500/10 text-amber-100'}`}><div className="min-w-0 flex-1"><p className="font-medium">{idea.plan.trip_sync.status==='synced'?'Program je rozdělený do celé cesty':'Čeká na dokončení databázových migrací'}</p><p className="mt-1 opacity-75">{idea.plan.trip_sync.status==='synced'?`${idea.plan.trip_sync.activities} bodů itineráře · ${idea.plan.trip_sync.expenses} položek rozpočtu · ${idea.plan.trip_sync.packing_items} položek přípravy`:idea.plan.trip_sync.message}</p></div><Link href={`/trips/${idea.plan.trip_sync.trip_id}/plan`} className="shrink-0 rounded-lg border border-current/25 px-3 py-2 text-center">Otevřít itinerář →</Link></div>}
        </div>
        <div className="border-t border-pink-400/15 bg-black/10 p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start"><div className="min-w-0 flex-1"><p className="text-xs font-medium uppercase tracking-wide text-pink-200">Jeden životní cyklus zážitku</p><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-5">{steps.map(step=><div key={step.label} className={`rounded-lg border p-2 text-[10px] ${step.done?'border-emerald-400/20 bg-emerald-500/10 text-emerald-100':'border-[var(--color-border)] text-[var(--color-text-secondary)]'}`}>{step.done?<Check size={12} className="mr-1 inline"/>:'○ '}{step.label}</div>)}</div>{!isFuture&&<div className="mt-3 flex flex-wrap gap-2"><a href="#event-reflection" className="inline-flex min-h-9 items-center rounded-lg border border-amber-400/30 bg-amber-500/10 px-3 text-xs text-amber-100">Společné ohlédnutí</a>{experience.memory&&<Link href="/shared-memories" className="inline-flex min-h-9 items-center rounded-lg border border-pink-400/30 px-3 text-xs text-pink-100">Otevřít vzpomínku</Link>}</div>}</div>
                {isFuture?<div className="w-full rounded-xl border border-pink-300/20 bg-pink-500/5 p-3 text-xs text-pink-100 lg:w-72"><Heart size={15}/><p className="mt-2 font-medium">Po randíčku se vraťte sem</p><p className="mt-1 text-pink-100/75">Galerie najde fotky podle času a místa, oba přidáte vlastní dojem a z jedné akce vznikne společné album.</p></div>:<form onSubmit={save} className="w-full rounded-xl border border-pink-300/20 bg-pink-500/5 p-3 lg:w-80"><p className="text-sm font-medium text-white">Jaké to bylo za mě?</p><div className="mt-2 flex gap-1">{[1,2,3,4,5].map(value=><button type="button" key={value} onClick={()=>{setRating(value);setReaction(value>=4?'love':value===3?'maybe':'pass');}} className={`h-9 w-9 rounded-lg ${rating>=value?'bg-pink-500/25 text-pink-200':'bg-black/10 text-[var(--color-text-secondary)]'}`}>★</button>)}</div><div className="mt-2 flex gap-1">{([['love','💞 Zopakovat'],['maybe','🤔 Možná'],['pass','Jiný typ']] as const).map(([value,label])=><button type="button" key={value} onClick={()=>setReaction(value)} className={`rounded-lg border px-2 py-1 text-[10px] ${reaction===value?'border-pink-300 bg-pink-500/15 text-white':'border-[var(--color-border)] text-[var(--color-text-secondary)]'}`}>{label}</button>)}</div><textarea value={note} onChange={event=>setNote(event.target.value)} rows={2} maxLength={500} placeholder="Co zachovat nebo příště změnit?" className="mt-2 w-full resize-none rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-xs text-white"/><button disabled={saving||!rating} className="mt-2 inline-flex min-h-9 items-center gap-1 rounded-lg bg-pink-600 px-3 text-xs text-white disabled:opacity-40"><Save size={13}/>{saving?'Ukládám…':'Uložit můj pohled'}</button>{message&&<p className={`mt-2 text-[10px] ${message.startsWith('Váš')?'text-emerald-200':'text-red-200'}`}>{message}</p>}</form>}
            </div>{idea.reactions.length>0&&<div className="mt-4 border-t border-pink-400/15 pt-3"><div className="flex flex-wrap items-center gap-2 text-xs"><span className="text-[var(--color-text-secondary)]">Naše pohledy:</span>{idea.reactions.map(item=><span key={item.user_id} className="rounded-full bg-black/15 px-2 py-1 text-pink-100">{item.user_name}: {item.rating?`${item.rating}/5 · `:''}{item.reaction==='love'?'zopakovat':item.reaction==='maybe'?'možná':'jiný typ'}</span>)}{idea.feedback.average_rating&&<span className="text-amber-200">průměr {idea.feedback.average_rating}/5</span>}</div></div>}
        </div>
    </section>;
}
function Metric({icon:Icon,value,label}:{icon:any;value:string;label:string}){return <div className="min-w-0 rounded-xl bg-black/10 p-2"><Icon size={13} className="text-pink-200"/><p className="mt-1 truncate text-xs font-medium text-white" title={value}>{value}</p><p className="truncate text-[9px] text-[var(--color-text-secondary)]">{label}</p></div>}
function money(value:number){return Math.round(Number(value||0)).toLocaleString('cs-CZ')}
function duration(minutes:number){return minutes>=1440?`${Math.round(minutes/1440)} dny`:minutes>=60?`${Math.floor(minutes/60)} h${minutes%60?` ${minutes%60} min`:''}`:`${minutes} min`}
function scope(value:string){return ({home:'Doma',nearby:'V okolí',city:'Po městě',day_trip:'Jednodenně',weekend:'Víkend'} as Record<string,string>)[value]??value}
function transport(value:string){return ({walk:'pěšky',bike:'na kole',transit:'MHD / bus',car:'autem',train:'vlakem'} as Record<string,string>)[value]??value}
