import axios from 'axios';
import { Link } from '@inertiajs/react';
import { CalendarHeart, Check, Heart, LoaderCircle, Play, Sparkles, X } from 'lucide-react';
import { useEffect, useState } from 'react';

type MemorySource={fingerprint:string;type:string;title:string;subtitle:string;items:Array<{uuid:string;taken_at?:string|null}>};
type EveningMedia={uuid:string;media_type:string;title:string;taken_at?:string;thumbnail_url?:string;detail_url:string;status:string;selected_count:number;my_vote:boolean|null};
type Reflection={user_id:number;user_name:string;mood?:string;note?:string;is_mine:boolean};
type Evening={uuid:string;title:string;description?:string;source_type:string;scheduled_for:string;status:'planned'|'active'|'completed'|'cancelled';repeat_annually:boolean;event?:{uuid:string;href:string};album?:{uuid:string;href:string};shared_memory?:{uuid:string;href:string};items:EveningMedia[];reflections:Reflection[];my_reflection?:Reflection|null};

const field='min-h-10 rounded-xl border border-[var(--color-border)] bg-black/10 px-3 text-sm text-white';
const MOODS:Record<string,string>={joyful:'😊 Radost',cozy:'🕯️ Pohoda',grateful:'💗 Vděčnost',funny:'😄 Smích',nostalgic:'📼 Nostalgie',moved:'🥹 Dojetí'};
const localInput=(iso?:string)=>{if(!iso)return'';const date=new Date(iso);const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16);};

export default function MemoryEveningPanel({spaceId,source,onClose}:{spaceId:number|null;source:MemorySource|null;onClose:()=>void}) {
    const [items,setItems]=useState<Evening[]>([]);const [suggested,setSuggested]=useState('');const [selected,setSelected]=useState<string>('');const [busy,setBusy]=useState('');const [error,setError]=useState('');
    const [schedule,setSchedule]=useState({scheduled_for:'',repeat_annually:false,description:''});const [reflection,setReflection]=useState({mood:'grateful',note:''});
    const load=async(focus?:string)=>{if(!spaceId)return;try{const response=await axios.get('/api/v1/memory-evenings',{params:{gallery_space_id:spaceId}});setItems(response.data.items??[]);setSuggested(response.data.suggested_for??'');if(focus)setSelected(focus);setError('');}catch(reason:any){setError(reason?.response?.data?.message??'Vzpomínkové večery se nepodařilo načíst.');}};
    useEffect(()=>{load();},[spaceId]);
    useEffect(()=>{if(source)setSchedule(current=>({...current,scheduled_for:current.scheduled_for||localInput(suggested)}));},[source,suggested]);
    const active=items.find(item=>item.uuid===selected)??items.find(item=>item.status==='active')??items.find(item=>item.status==='planned');
    useEffect(()=>{if(active?.my_reflection)setReflection({mood:active.my_reflection.mood??'grateful',note:active.my_reflection.note??''});},[active?.uuid,active?.my_reflection?.note]);
    const plan=async()=>{if(!spaceId||!source)return;setBusy('plan');try{const response=await axios.post('/api/v1/memory-evenings',{gallery_space_id:spaceId,fingerprint:source.fingerprint,source_type:source.type,title:source.title,description:schedule.description||source.subtitle,source_happened_on:source.items[0]?.taken_at?.slice(0,10)||null,scheduled_for:schedule.scheduled_for?new Date(schedule.scheduled_for).toISOString():null,repeat_annually:schedule.repeat_annually,media_uuids:source.items.map(item=>item.uuid)});onClose();setSchedule({scheduled_for:'',repeat_annually:false,description:''});await load(response.data.uuid);}catch(reason:any){setError(reason?.response?.data?.message??'Večer se nepodařilo naplánovat.');}finally{setBusy('');}};
    const action=async(path:string,key:string,method:'post'|'put'='post',payload:any={})=>{if(!active)return;setBusy(key);try{const response=await axios[method](`/api/v1/memory-evenings/${active.uuid}${path}`,payload);setItems(current=>current.map(item=>item.uuid===active.uuid?response.data:item));setError('');}catch(reason:any){setError(reason?.response?.data?.message??'Změnu se nepodařilo uložit.');}finally{setBusy('');}};
    const vote=async(media:EveningMedia)=>{setBusy(media.uuid);try{const response=await axios.put(`/api/v1/memory-evenings/${active!.uuid}/media/${media.uuid}`,{is_selected:media.my_vote!==true});setItems(current=>current.map(item=>item.uuid===active!.uuid?response.data:item));}catch(reason:any){setError(reason?.response?.data?.message??'Výběr se nepodařilo uložit.');}finally{setBusy('');}};
    const saveReflection=()=>action('/reflection','reflection','put',reflection);
    return <section id="memory-evenings" className="rounded-3xl border border-pink-400/25 bg-gradient-to-br from-pink-500/10 via-[var(--color-bg-card)] to-violet-500/5 p-4 sm:p-5">
        <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-pink-200"><CalendarHeart size={15}/>Partnerský rituál</p><h2 className="mt-1 text-lg font-semibold text-white">Večer se vzpomínkami</h2><p className="mt-1 max-w-2xl text-sm text-[var(--color-text-secondary)]">Galerie připraví momenty, kalendář najde společný večer a váš společný výběr se po dokončení promění v album i trvalou vzpomínku.</p></div>{suggested&&<p className="rounded-xl bg-pink-500/10 px-3 py-2 text-xs text-pink-100">Nejbližší volno<br/><b>{new Date(suggested).toLocaleString('cs-CZ',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}</b></p>}</div>
        {error&&<p className="mt-3 rounded-lg bg-red-500/10 p-3 text-xs text-red-200">{error}</p>}
        {items.length>0&&<div className="mt-4 flex gap-2 overflow-x-auto pb-1">{items.map(item=><button key={item.uuid} onClick={()=>setSelected(item.uuid)} className={`min-w-48 rounded-xl border p-3 text-left ${active?.uuid===item.uuid?'border-pink-300/50 bg-pink-500/10':'border-[var(--color-border)] bg-black/10'}`}><p className="truncate text-sm font-medium text-white">{item.title}</p><p className="mt-1 text-[10px] text-[var(--color-text-secondary)]">{item.status==='active'?'právě probíhá':item.status==='completed'?'dokončeno':item.status==='cancelled'?'zrušeno':new Date(item.scheduled_for).toLocaleString('cs-CZ',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</p></button>)}</div>}
        {active&&<div className="mt-4 rounded-2xl border border-white/5 bg-black/10 p-3 sm:p-4"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><h3 className="font-medium text-white">{active.title}</h3><p className="text-xs text-[var(--color-text-secondary)]">{new Date(active.scheduled_for).toLocaleString('cs-CZ',{dateStyle:'long',timeStyle:'short'})} · {active.items.length} momentů{active.repeat_annually?' · každý rok':''}</p></div><div className="flex flex-wrap gap-2">{active.event&&<Link href={active.event.href} className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-xs text-white">Kalendář</Link>}{active.status==='planned'&&<button disabled={!!busy} onClick={()=>action('/start','start')} className="rounded-lg bg-pink-500 px-3 py-2 text-xs font-medium text-white"><Play size={13} className="mr-1 inline"/>Spustit večer</button>}{active.status==='completed'&&active.album&&<Link href={active.album.href} className="rounded-lg bg-pink-500 px-3 py-2 text-xs text-white">Otevřít společné album</Link>}</div></div>
            {active.status!=='cancelled'&&<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{active.items.map(media=><button key={media.uuid} disabled={active.status==='completed'||busy===media.uuid} onClick={()=>vote(media)} className={`group relative aspect-square overflow-hidden rounded-xl border ${media.my_vote===true?'border-pink-300 ring-2 ring-pink-400/30':'border-[var(--color-border)]'} disabled:cursor-default`}><img src={media.thumbnail_url} alt={media.title} loading="lazy" className="h-full w-full object-cover"/><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/90 to-transparent p-2 pt-8 text-left text-[10px] text-white"><span className="line-clamp-2">{media.title}</span><span className="mt-1 flex items-center gap-1 text-pink-200"><Heart size={11} className={media.my_vote===true?'fill-pink-300':''}/>{media.selected_count}× vybráno</span></span>{busy===media.uuid&&<span className="absolute inset-0 grid place-items-center bg-black/50"><LoaderCircle className="animate-spin"/></span>}</button>)}</div>}
            {active.status!=='cancelled'&&<div className="mt-4 grid gap-3 lg:grid-cols-[minmax(0,1fr)_auto]"><div className="grid gap-2 sm:grid-cols-[auto_minmax(0,1fr)]"><select value={reflection.mood} onChange={event=>setReflection({...reflection,mood:event.target.value})} className={field}>{Object.entries(MOODS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><textarea value={reflection.note} onChange={event=>setReflection({...reflection,note:event.target.value})} placeholder="Co v nás tyto momenty vyvolávají?" rows={2} className={`${field} h-auto py-2`}/></div><button disabled={busy==='reflection'} onClick={saveReflection} className="rounded-xl border border-pink-300/30 px-4 py-2 text-xs text-pink-100">{busy==='reflection'?'Ukládám…':'Uložit můj pohled'}</button></div>}
            {active.reflections.length>0&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{active.reflections.map(item=><div key={item.user_id} className="rounded-xl bg-white/5 p-3 text-xs text-[var(--color-text-secondary)]"><b className="text-white">{item.user_name}</b> · {MOODS[item.mood??'']??item.mood}<p className="mt-1 text-white/80">{item.note}</p></div>)}</div>}
            {active.status==='active'&&<button disabled={busy==='complete'} onClick={()=>action('/complete','complete')} className="mt-4 w-full rounded-xl bg-gradient-to-r from-pink-500 to-violet-500 px-4 py-3 text-sm font-medium text-white"><Check size={16} className="mr-2 inline"/>{busy==='complete'?'Vytvářím album a vzpomínku…':'Dokončit a vytvořit společné album'}</button>}
        </div>}
        {!items.length&&!source&&<p className="mt-4 rounded-xl border border-dashed border-pink-300/20 p-5 text-center text-sm text-[var(--color-text-secondary)]">U některého výběru níže zvolte „Naplánovat večer“. Nabídneme první společný termín bez kolize.</p>}
        {source&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div className="w-full max-w-lg rounded-t-3xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-5 sm:rounded-3xl"><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wide text-pink-200">Naplánovat pro oba</p><h3 className="mt-1 text-lg font-semibold text-white">{source.title}</h3><p className="mt-1 text-xs text-[var(--color-text-secondary)]">{source.items.length} fotografií a videí zůstane v původní galerii; vytváří se jen propojený výběr.</p></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl border border-[var(--color-border)]"><X size={17}/></button></div><label className="mt-4 block text-xs text-[var(--color-text-secondary)]">Datum a čas<input type="datetime-local" value={schedule.scheduled_for||localInput(suggested)} onChange={event=>setSchedule({...schedule,scheduled_for:event.target.value})} className={`${field} mt-1 w-full`}/></label><label className="mt-3 block text-xs text-[var(--color-text-secondary)]">Společná poznámka<textarea value={schedule.description} onChange={event=>setSchedule({...schedule,description:event.target.value})} rows={3} placeholder="Co si chceme společně připomenout?" className={`${field} mt-1 h-auto w-full py-2`}/></label><label className="mt-3 flex items-center gap-2 rounded-xl border border-[var(--color-border)] p-3 text-sm text-white"><input type="checkbox" checked={schedule.repeat_annually} onChange={event=>setSchedule({...schedule,repeat_annually:event.target.checked})}/> Udělat z večera každoroční partnerský rituál</label><button disabled={busy==='plan'} onClick={plan} className="mt-4 min-h-11 w-full rounded-xl bg-gradient-to-r from-pink-500 to-violet-500 text-sm font-medium text-white disabled:opacity-50"><Sparkles size={16} className="mr-2 inline"/>{busy==='plan'?'Propojuji kalendář a galerii…':'Naplánovat společný večer'}</button></div></div>}
    </section>;
}
