import axios from 'axios';
import { Link } from '@inertiajs/react';
import { CalendarPlus, Check, ChevronDown, Circle, Clapperboard, Film, ListTodo, Plus, RefreshCw, Search, Star, Tv, Users } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';

type Member = { id:number; name:string };
type TodoList = { uuid:string; title:string; color:string; icon:string };
type Todo = { uuid:string; title:string; description?:string; status:string; priority:string; due_at?:string; remind_at?:string; assigned_to?:number; assignee?:Member; list?:TodoList; recurrence?:{frequency:string;interval?:number}; is_blocked:boolean; dependencies?:Array<{uuid:string;title:string;status:string}>; children?:Todo[]; comments?:Array<{uuid:string;body:string;user?:Member}>; href:string };
type Proposal = { uuid:string; starts_at:string; venue:string; place_name?:string; status:string; booking_url?:string; votes?:Record<string,number>; my_response?:string; event_uuid?:string };
type Title = { uuid:string; media_type:'movie'|'series'; title:string; original_title?:string; overview?:string; poster_url?:string; release_year?:number; runtime_minutes?:number; status:string; priority:string; joint_score?:number; my_vote?:{interest:number;cinema_preferred:boolean}; proposals:Proposal[] };
type Showing = { uuid:string; title:string; starts_at:string; poster_url?:string; runtime_minutes?:number; format?:string; dubbed_language?:string; subtitles_language?:string; sold_out:boolean; availability_ratio?:number; booking_url?:string; source_url:string };
type SearchResult = Partial<Title>&{title:string;media_type:'movie'|'series';external_source?:string;external_id?:string;already_added?:boolean};
type DateSuggestion = { starts_at:string; venue:string; label?:string; uuid?:string; title?:string; booking_url?:string };

const field='min-h-10 rounded-lg border border-[var(--color-border)] bg-black/10 px-3 text-sm text-white placeholder:text-[var(--color-text-secondary)]';
const card='rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4';
const formatDate=(value?:string, options?:Intl.DateTimeFormatOptions)=>value?new Date(value).toLocaleString('cs-CZ',options??{dateStyle:'medium',timeStyle:'short'}):'bez termínu';

export default function TodoEntertainmentPlanner({spaceId}:{spaceId?:number}) {
    if(!spaceId) return null;
    return <div className="mt-5 space-y-5"><TodoPlanner spaceId={spaceId}/><EntertainmentPlanner spaceId={spaceId}/></div>;
}

export function TodoPlanner({spaceId}:{spaceId:number}) {
    const [data,setData]=useState<{lists:TodoList[];tasks:Todo[];members:Member[];summary:any}>({lists:[],tasks:[],members:[],summary:{}});
    const [scope,setScope]=useState('all'); const [status,setStatus]=useState('active'); const [search,setSearch]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
    const [form,setForm]=useState({title:'',description:'',list_uuid:'',assigned_to:'',priority:'normal',due_at:'',remind_at:'',estimate_minutes:'60',recurrence:'none',calendar:false});
    const [newList,setNewList]=useState(''); const [expanded,setExpanded]=useState<string|null>(null); const [comment,setComment]=useState(''); const [subtask,setSubtask]=useState('');
    const load=async()=>{try{const response=await axios.get('/api/v1/todos',{params:{gallery_space_id:spaceId,scope,status,search:search||undefined}});setData(response.data);if(!form.list_uuid&&response.data.lists?.[0])setForm(current=>({...current,list_uuid:response.data.lists[0].uuid}));setError('');}catch(reason:any){setError(reason?.response?.data?.message??'Úkoly se nepodařilo načíst.');}};
    useEffect(()=>{const timer=setTimeout(load,search?250:0);return()=>clearTimeout(timer);},[spaceId,scope,status,search]);
    const create=async(e:FormEvent)=>{e.preventDefault();if(!form.title.trim())return;setBusy(true);try{await axios.post('/api/v1/todos',{gallery_space_id:spaceId,title:form.title,description:form.description||null,list_uuid:form.list_uuid||null,assigned_to:form.assigned_to?Number(form.assigned_to):null,priority:form.priority,due_at:form.due_at||null,remind_at:form.remind_at||null,estimate_minutes:Number(form.estimate_minutes)||null,recurrence:form.recurrence==='none'?null:{frequency:form.recurrence,interval:1},create_calendar_event:form.calendar});setForm(current=>({...current,title:'',description:'',due_at:'',remind_at:'',calendar:false}));await load();}catch(reason:any){setError(reason?.response?.data?.message??'Úkol se nepodařilo uložit.');}finally{setBusy(false);}};
    const addList=async()=>{if(!newList.trim())return;try{const response=await axios.post('/api/v1/todo-lists',{gallery_space_id:spaceId,title:newList});setNewList('');setForm(current=>({...current,list_uuid:response.data.uuid}));await load();}catch(reason:any){setError(reason?.response?.data?.message??'Seznam se nepodařilo vytvořit.');}};
    const patch=async(uuid:string,payload:any)=>{try{await axios.patch(`/api/v1/todos/${uuid}`,payload);await load();}catch(reason:any){setError(reason?.response?.data?.message??'Změnu se nepodařilo uložit.');}};
    const schedule=async(uuid:string)=>{try{await axios.post(`/api/v1/todos/${uuid}/schedule`);await load();}catch(reason:any){setError(reason?.response?.data?.message??'Termín se nepodařilo přidat do kalendáře.');}};
    const addComment=async(uuid:string)=>{if(!comment.trim())return;await axios.post(`/api/v1/todos/${uuid}/comments`,{body:comment});setComment('');await load();};
    const addSubtask=async(todo:Todo)=>{if(!subtask.trim())return;await axios.post('/api/v1/todos',{gallery_space_id:spaceId,title:subtask,parent_uuid:todo.uuid,list_uuid:todo.list?.uuid,assigned_to:todo.assigned_to??null});setSubtask('');await load();};
    return <section id="todos" className={card}>
        <div className="flex flex-col justify-between gap-3 lg:flex-row lg:items-start"><div><h2 className="flex items-center gap-2 text-lg font-semibold text-white"><ListTodo size={20} className="text-teal-300"/>Společné úkoly</h2><p className="mt-1 max-w-3xl text-sm text-[var(--color-text-secondary)]">Jednorázové i opakované úkoly, rozdělení odpovědnosti, podúkoly, závislosti, připomínky a přímé napojení na kalendář.</p></div><div className="grid grid-cols-4 gap-2 text-center text-xs"><Metric value={data.summary.active} label="aktivní"/><Metric value={data.summary.mine} label="moje"/><Metric value={data.summary.unassigned} label="volné"/><Metric value={data.summary.overdue} label="po termínu" danger/></div></div>
        {error&&<p className="mt-3 rounded-lg bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
        <form onSubmit={create} className="mt-4 grid gap-2 rounded-xl border border-teal-400/20 bg-teal-500/5 p-3 md:grid-cols-2 xl:grid-cols-4">
            <input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Co potřebujeme zařídit?" className={`${field} md:col-span-2`}/>
            <select value={form.list_uuid} onChange={e=>setForm({...form,list_uuid:e.target.value})} className={field}><option value="">Společné úkoly</option>{data.lists.map(list=><option key={list.uuid} value={list.uuid}>{list.icon} {list.title}</option>)}</select>
            <select value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})} className={field}><option value="">Domluvit společně</option>{data.members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select>
            <select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className={field}><option value="low">Nízká priorita</option><option value="normal">Běžná priorita</option><option value="high">Vysoká priorita</option><option value="urgent">Urgentní</option></select>
            <label className="text-xs text-[var(--color-text-secondary)]">Termín<input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})} className={`${field} mt-1 w-full`}/></label>
            <label className="text-xs text-[var(--color-text-secondary)]">Připomenout<input type="datetime-local" value={form.remind_at} max={form.due_at||undefined} onChange={e=>setForm({...form,remind_at:e.target.value})} className={`${field} mt-1 w-full`}/></label>
            <select value={form.recurrence} onChange={e=>setForm({...form,recurrence:e.target.value})} className={field}><option value="none">Neopakovat</option><option value="daily">Každý den</option><option value="weekly">Každý týden</option><option value="monthly">Každý měsíc</option><option value="yearly">Každý rok</option></select>
            <textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Detaily nebo společná domluva" rows={2} className={`${field} h-auto md:col-span-2`}/>
            <label className="flex min-h-10 items-center gap-2 rounded-lg border border-[var(--color-border)] px-3 text-sm text-white"><input type="checkbox" checked={form.calendar} onChange={e=>setForm({...form,calendar:e.target.checked})}/> rovnou do kalendáře</label>
            <button disabled={busy} className="min-h-10 rounded-lg bg-teal-500 px-4 text-sm font-medium text-white disabled:opacity-50"><Plus size={16} className="mr-1 inline"/>{busy?'Ukládám…':'Přidat úkol'}</button>
        </form>
        <div className="mt-3 flex flex-wrap gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Hledat v úkolech" className={`${field} min-w-48 flex-1`}/><select value={scope} onChange={e=>setScope(e.target.value)} className={field}><option value="all">Všechny odpovědnosti</option><option value="mine">Moje úkoly</option><option value="unassigned">Bez odpovědnosti</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className={field}><option value="active">Aktivní</option><option value="completed">Dokončené</option><option value="waiting">Čekající</option><option value="cancelled">Zrušené</option></select></div>
        <div className="mt-4 grid gap-2 lg:grid-cols-2">{data.tasks.map(todo=><article key={todo.uuid} className={`rounded-xl border p-3 ${todo.priority==='urgent'?'border-red-400/40 bg-red-500/5':'border-[var(--color-border)] bg-black/10'}`}>
            <div className="flex gap-3"><button aria-label={todo.status==='completed'?'Obnovit úkol':'Dokončit úkol'} onClick={()=>patch(todo.uuid,{completed:todo.status!=='completed'})} className="mt-0.5 shrink-0 text-teal-300">{todo.status==='completed'?<Check size={21}/>:<Circle size={21}/>}</button><button onClick={()=>setExpanded(expanded===todo.uuid?null:todo.uuid)} className="min-w-0 flex-1 text-left"><div className="flex flex-wrap items-center gap-2"><span className={`font-medium ${todo.status==='completed'?'text-[var(--color-text-secondary)] line-through':'text-white'}`}>{todo.title}</span><Priority value={todo.priority}/>{todo.recurrence&&<span className="rounded bg-violet-500/15 px-2 py-0.5 text-[10px] text-violet-200">opakovaně</span>}{todo.is_blocked&&<span className="rounded bg-amber-500/15 px-2 py-0.5 text-[10px] text-amber-200">čeká na jiný úkol</span>}</div><p className="mt-1 text-xs text-[var(--color-text-secondary)]">{todo.list?.icon} {todo.list?.title??'Společné úkoly'} · {todo.assignee?.name??'společně'} · {formatDate(todo.due_at)}</p></button><ChevronDown size={16} className={`mt-1 text-[var(--color-text-secondary)] transition ${expanded===todo.uuid?'rotate-180':''}`}/></div>
            {expanded===todo.uuid&&<div className="mt-3 border-t border-[var(--color-border)] pt-3"><p className="text-sm text-[var(--color-text-secondary)]">{todo.description||'Bez doplňujících poznámek.'}</p><div className="mt-2 flex flex-wrap gap-2"><select aria-label="Přiřadit úkol" value={todo.assigned_to??''} onChange={e=>patch(todo.uuid,{assigned_to:e.target.value?Number(e.target.value):null})} className={`${field} min-h-9 py-1 text-xs`}><option value="">Společně</option>{data.members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select>{todo.href.startsWith('/calendar/')?<Link href={todo.href} className="rounded-lg border border-violet-400/30 px-3 py-2 text-xs text-violet-200">Otevřít v kalendáři</Link>:<button onClick={()=>schedule(todo.uuid)} className="rounded-lg border border-violet-400/30 px-3 py-2 text-xs text-violet-200"><CalendarPlus size={14} className="mr-1 inline"/>Do kalendáře</button>}</div>{todo.children?.map(child=><div key={child.uuid} className="mt-2 flex items-center gap-2 rounded-lg bg-black/15 p-2 text-xs text-white"><button onClick={()=>patch(child.uuid,{completed:child.status!=='completed'})}>{child.status==='completed'?<Check size={15}/>:<Circle size={15}/>}</button><span className={child.status==='completed'?'line-through opacity-60':''}>{child.title}</span></div>)}<div className="mt-2 flex gap-2"><input value={subtask} onChange={e=>setSubtask(e.target.value)} placeholder="Nový podúkol" className={`${field} min-w-0 flex-1 min-h-9`}/><button onClick={()=>addSubtask(todo)} className="rounded-lg border border-[var(--color-border)] px-3 text-sm text-white">Přidat</button></div>{todo.comments?.map(entry=><p key={entry.uuid} className="mt-2 rounded-lg bg-black/15 p-2 text-xs text-[var(--color-text-secondary)]"><b className="text-white">{entry.user?.name}:</b> {entry.body}</p>)}<div className="mt-2 flex gap-2"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Komentář k domluvě" className={`${field} min-w-0 flex-1 min-h-9`}/><button onClick={()=>addComment(todo.uuid)} className="rounded-lg border border-[var(--color-border)] px-3 text-sm text-white">Odeslat</button></div></div>}
        </article>)}{!data.tasks.length&&<p className="rounded-xl border border-dashed border-[var(--color-border)] p-6 text-center text-sm text-[var(--color-text-secondary)] lg:col-span-2">V tomto pohledu nejsou žádné úkoly.</p>}</div>
        <div className="mt-3 flex gap-2"><input value={newList} onChange={e=>setNewList(e.target.value)} placeholder="Nový tematický seznam (domov, cesta, nákup…)" className={`${field} min-w-0 flex-1`}/><button onClick={addList} className="rounded-lg border border-[var(--color-border)] px-3 text-sm text-white">Vytvořit seznam</button></div>
    </section>;
}

export function EntertainmentPlanner({spaceId}:{spaceId:number}) {
    const [titles,setTitles]=useState<Title[]>([]); const [showings,setShowings]=useState<Showing[]>([]); const [members,setMembers]=useState<Member[]>([]); const [tmdb,setTmdb]=useState(false); const [query,setQuery]=useState(''); const [results,setResults]=useState<SearchResult[]>([]); const [error,setError]=useState(''); const [syncing,setSyncing]=useState(false); const [type,setType]=useState('all'); const [status,setStatus]=useState('all');
    const [suggestions,setSuggestions]=useState<Record<string,{home:DateSuggestion[];cinema:DateSuggestion[]}>>({}); const [manualDate,setManualDate]=useState<Record<string,string>>({}); const [rating,setRating]=useState<Record<string,string>>({});
    const load=async()=>{try{const response=await axios.get('/api/v1/entertainment',{params:{gallery_space_id:spaceId,status,type:type==='all'?undefined:type}});setTitles(response.data.titles??[]);setShowings(response.data.cinema?.showings??[]);setMembers(response.data.members??[]);setTmdb(Boolean(response.data.integrations?.tmdb_configured));setError('');}catch(reason:any){setError(reason?.response?.data?.message??'Filmový plán se nepodařilo načíst.');}};
    useEffect(()=>{load();},[spaceId,type,status]);
    useEffect(()=>{if(query.trim().length<2){setResults([]);return;}const timer=setTimeout(async()=>{try{const response=await axios.get('/api/v1/entertainment/search',{params:{query}});setResults(response.data.results??[]);setTmdb(Boolean(response.data.tmdb_configured));}catch{setResults([]);}},350);return()=>clearTimeout(timer);},[query]);
    const add=async(item:SearchResult)=>{try{await axios.post('/api/v1/entertainment',{gallery_space_id:spaceId,...item,status:undefined,proposals:undefined});setQuery('');setResults([]);await load();}catch(reason:any){setError(reason?.response?.data?.message??'Titul se nepodařilo přidat.');}};
    const addManual=async()=>{if(!query.trim())return;await add({title:query.trim(),media_type:'movie',external_source:'manual'});};
    const vote=async(title:Title,interest:number)=>{await axios.put(`/api/v1/entertainment/${title.uuid}/vote`,{interest,cinema_preferred:title.my_vote?.cinema_preferred??false});await load();};
    const findDates=async(title:Title)=>{const response=await axios.get(`/api/v1/entertainment/${title.uuid}/date-suggestions`);setSuggestions(current=>({...current,[title.uuid]:response.data}));};
    const propose=async(title:Title,suggestion:DateSuggestion)=>{await axios.post(`/api/v1/entertainment/${title.uuid}/date-proposals`,suggestion.uuid?{showing_uuid:suggestion.uuid}:{starts_at:suggestion.starts_at,venue:suggestion.venue});await load();};
    const proposeManual=async(title:Title)=>{if(!manualDate[title.uuid])return;await propose(title,{starts_at:manualDate[title.uuid],venue:'home'});setManualDate(current=>({...current,[title.uuid]:''}));};
    const voteProposal=async(uuid:string,response:string)=>{await axios.put(`/api/v1/entertainment/date-proposals/${uuid}/vote`,{response});await load();};
    const selectProposal=async(uuid:string)=>{await axios.post(`/api/v1/entertainment/date-proposals/${uuid}/select`);await load();};
    const sync=async()=>{setSyncing(true);try{const response=await axios.post('/api/v1/entertainment/cinema/sync',{days:10});await load();const warnings=response.data.warnings??[];if(warnings.length)setError(`Program byl načten částečně. ${warnings[0]}`);}catch(reason:any){const message=reason?.response?.data?.message??'Program kina se nepodařilo obnovit.';const detail=reason?.response?.data?.reason;setError(detail?`${message} Důvod: ${detail}`:message);}finally{setSyncing(false);}};
    const addShowing=async(showing:Showing)=>{await axios.post(`/api/v1/entertainment/cinema/showings/${showing.uuid}`,{gallery_space_id:spaceId,propose:true});await load();};
    const watched=async(title:Title)=>{await axios.post(`/api/v1/entertainment/${title.uuid}/sessions`,{watched_at:new Date().toISOString(),rating:rating[title.uuid]?Number(rating[title.uuid]):null});await load();};
    const groupedShowings=useMemo(()=>showings.reduce<Record<string,Showing[]>>((groups,item)=>{const key=new Date(item.starts_at).toLocaleDateString('cs-CZ',{weekday:'short',day:'numeric',month:'numeric'});(groups[key]??=[]).push(item);return groups;},{}),[showings]);
    return <section id="watchlist" className={card}>
        <div className="flex flex-col justify-between gap-3 lg:flex-row"><div><h2 className="flex items-center gap-2 text-lg font-semibold text-white"><Clapperboard size={20} className="text-violet-300"/>Co uvidíme spolu</h2><p className="mt-1 max-w-3xl text-sm text-[var(--color-text-secondary)]">Společná fronta filmů a seriálů, hodnocení zájmu, volné večery, hlasování o termínu, kino a následný zápis do kalendáře.</p></div><div className="flex gap-2"><select value={type} onChange={e=>setType(e.target.value)} className={field}><option value="all">Filmy i seriály</option><option value="movie">Filmy</option><option value="series">Seriály</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className={field}><option value="all">Všechny stavy</option><option value="proposed">Navržené</option><option value="scheduled">Naplánované</option><option value="watching">Rozkoukané</option><option value="watched">Zhlédnuté</option></select></div></div>
        {error&&<p className="mt-3 rounded-lg bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
        <div className="relative mt-4"><Search size={17} className="absolute left-3 top-3 text-[var(--color-text-secondary)]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Najít film nebo seriál v globální databázi…" className={`${field} w-full pl-10`}/>{query.length>=2&&<div className="absolute z-30 mt-1 max-h-96 w-full overflow-y-auto rounded-xl border border-[var(--color-border)] bg-[var(--color-bg-secondary)] p-2 shadow-2xl">{results.map((item,index)=><button key={`${item.external_source}-${item.external_id}-${index}`} disabled={item.already_added} onClick={()=>add(item)} className="flex w-full items-center gap-3 rounded-lg p-2 text-left hover:bg-white/5 disabled:opacity-50">{item.poster_url?<img src={item.poster_url} alt="" loading="lazy" className="h-16 w-11 rounded object-cover"/>:<div className="grid h-16 w-11 place-items-center rounded bg-black/20"><Film size={17}/></div>}<span className="min-w-0 flex-1"><b className="block truncate text-sm text-white">{item.title}</b><small className="text-[var(--color-text-secondary)]">{item.media_type==='series'?'seriál':'film'} {item.release_year?`· ${item.release_year}`:''}</small></span><Plus size={16}/></button>)}<button onClick={addManual} className="mt-1 w-full rounded-lg border border-dashed border-[var(--color-border)] p-2 text-sm text-white">Přidat „{query}“ ručně</button>{!tmdb&&<p className="p-2 text-xs text-amber-200">Globální našeptávač vyžaduje TMDB klíč. <Link href="/admin/integrations#tmdb" className="font-medium underline">Otevřít konfiguraci TMDB</Link>. Ruční seznam funguje i bez něj.</p>}</div>}</div>
        <div className="mt-4 grid gap-3 lg:grid-cols-2">{titles.map(title=><article key={title.uuid} className="overflow-hidden rounded-xl border border-[var(--color-border)] bg-black/10"><div className="flex gap-3 p-3">{title.poster_url?<img src={title.poster_url} alt={`Plakát ${title.title}`} loading="lazy" className="h-32 w-22 rounded-lg object-cover"/>:<div className="grid h-32 w-22 shrink-0 place-items-center rounded-lg bg-violet-500/10">{title.media_type==='series'?<Tv/>:<Film/>}</div>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium text-white">{title.title}</h3><span className="rounded bg-violet-500/15 px-2 py-0.5 text-[10px] text-violet-200">{title.media_type==='series'?'seriál':'film'}</span><span className="text-xs text-[var(--color-text-secondary)]">{title.release_year}</span></div><p className="mt-1 line-clamp-2 text-xs leading-relaxed text-[var(--color-text-secondary)]">{title.overview||'Bez anotace. Můžete jej přesto společně ohodnotit a naplánovat.'}</p><div className="mt-2 flex items-center gap-1" aria-label="Můj zájem">{[1,2,3,4,5].map(value=><button key={value} onClick={()=>vote(title,value)} aria-label={`Zájem ${value} z 5`}><Star size={18} className={value<=(title.my_vote?.interest??0)?'fill-amber-300 text-amber-300':'text-slate-500'}/></button>)}{title.joint_score&&<span className="ml-2 text-xs text-amber-200">společně {title.joint_score}/5</span>}</div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>findDates(title)} className="rounded-lg border border-violet-400/30 px-3 py-2 text-xs text-violet-100"><CalendarPlus size={14} className="mr-1 inline"/>Najít společný termín</button><select aria-label="Hodnocení po zhlédnutí" value={rating[title.uuid]??''} onChange={e=>setRating({...rating,[title.uuid]:e.target.value})} className={`${field} min-h-8 px-2 text-xs`}><option value="">hodnocení</option>{[1,2,3,4,5].map(value=><option key={value} value={value}>{value}/5</option>)}</select><button onClick={()=>watched(title)} className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-xs text-white">Právě zhlédnuto</button></div></div></div>
            {suggestions[title.uuid]&&<div className="border-t border-[var(--color-border)] p-3"><p className="text-xs font-medium uppercase tracking-wide text-[var(--color-text-secondary)]">Doporučené volné večery</p><div className="mt-2 flex flex-wrap gap-2">{suggestions[title.uuid].home.map(item=><button key={item.starts_at} onClick={()=>propose(title,item)} className="rounded-lg bg-teal-500/10 px-3 py-2 text-xs text-teal-100">{item.label??formatDate(item.starts_at)}</button>)}{suggestions[title.uuid].cinema.map(item=><button key={item.uuid} onClick={()=>propose(title,item)} className="rounded-lg bg-violet-500/10 px-3 py-2 text-xs text-violet-100">Kino · {formatDate(item.starts_at)}</button>)}</div><div className="mt-2 flex gap-2"><input type="datetime-local" value={manualDate[title.uuid]??''} onChange={e=>setManualDate({...manualDate,[title.uuid]:e.target.value})} className={`${field} min-w-0 flex-1`}/><button onClick={()=>proposeManual(title)} className="rounded-lg border border-[var(--color-border)] px-3 text-xs text-white">Navrhnout</button></div></div>}
            {!!title.proposals?.length&&<div className="border-t border-[var(--color-border)] p-3"><p className="flex items-center gap-1 text-xs font-medium text-white"><Users size={13}/>Domluva termínu</p>{title.proposals.map(proposal=><div key={proposal.uuid} className="mt-2 flex flex-col justify-between gap-2 rounded-lg bg-black/15 p-2 sm:flex-row sm:items-center"><div><p className="text-xs text-white">{formatDate(proposal.starts_at)} · {proposal.place_name||'doma'}</p><p className="text-[10px] text-[var(--color-text-secondary)]">ano {proposal.votes?.yes??0} · možná {proposal.votes?.maybe??0} · ne {proposal.votes?.no??0}</p></div><div className="flex flex-wrap gap-1">{proposal.booking_url&&<a href={proposal.booking_url} target="_blank" rel="noreferrer" className="rounded border border-violet-400/30 px-2 py-1 text-[10px] text-violet-100">Jízdenky</a>}{proposal.event_uuid?<Link href={`/calendar/events/${proposal.event_uuid}`} className="rounded border border-teal-400/30 px-2 py-1 text-[10px] text-teal-100">V kalendáři</Link>:<>{['yes','maybe','no'].map(response=><button key={response} onClick={()=>voteProposal(proposal.uuid,response)} className={`rounded border px-2 py-1 text-[10px] ${proposal.my_response===response?'border-white text-white':'border-[var(--color-border)] text-[var(--color-text-secondary)]'}`}>{response==='yes'?'mohu':response==='maybe'?'možná':'nemohu'}</button>)}<button onClick={()=>selectProposal(proposal.uuid)} className="rounded bg-teal-500 px-2 py-1 text-[10px] text-white">Potvrdit</button></>}</div></div>)}</div>}
        </article>)}{!titles.length&&<p className="rounded-xl border border-dashed border-[var(--color-border)] p-8 text-center text-sm text-[var(--color-text-secondary)] lg:col-span-2">Vyhledejte první film nebo seriál, který chcete vidět spolu.</p>}</div>
        <div className="mt-5 border-t border-[var(--color-border)] pt-4"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-center"><div><h3 className="font-medium text-white">Kino · Velký Špalíček Brno</h3><p className="text-xs text-[var(--color-text-secondary)]">Oficiální program je uložen do mezipaměti; rezervace vždy pokračuje na webu kina.</p></div><div className="flex gap-2"><a href="https://www.cinemacity.cz/cinemas/velkyspalicek/1035" target="_blank" rel="noreferrer" className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-xs text-white">Oficiální program</a><button type="button" onClick={sync} disabled={syncing} className="rounded-lg border border-violet-400/30 px-3 py-2 text-xs text-violet-100 disabled:opacity-50"><RefreshCw size={14} className={`mr-1 inline ${syncing?'animate-spin':''}`}/>{syncing?'Obnovuji…':'Obnovit program'}</button></div></div><div className="mt-3 max-h-[32rem] space-y-4 overflow-y-auto pr-1">{Object.entries(groupedShowings).map(([day,items])=><div key={day}><p className="sticky top-0 z-10 bg-[var(--color-bg-card)] py-1 text-xs font-medium uppercase text-violet-200">{day}</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map(showing=><article key={showing.uuid} className="flex gap-2 rounded-lg border border-[var(--color-border)] p-2">{showing.poster_url&&<img src={showing.poster_url} alt="" loading="lazy" className="h-20 w-14 rounded object-cover"/>}<div className="min-w-0 flex-1"><p className="line-clamp-2 text-xs font-medium text-white">{showing.title}</p><p className="mt-1 text-[10px] text-[var(--color-text-secondary)]">{new Date(showing.starts_at).toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'})} {showing.format?`· ${showing.format}`:''}</p><div className="mt-2 flex gap-1"><button type="button" disabled={showing.sold_out} onClick={()=>addShowing(showing)} className="rounded bg-violet-500/15 px-2 py-1 text-[10px] text-violet-100 disabled:opacity-40">Navrhnout termín</button>{showing.booking_url&&<a href={showing.booking_url} target="_blank" rel="noreferrer" className="rounded border border-[var(--color-border)] px-2 py-1 text-[10px] text-white">Rezervovat</a>}</div></div></article>)}</div></div>)}{!showings.length&&<p className="rounded-lg border border-dashed border-[var(--color-border)] p-5 text-center text-sm text-[var(--color-text-secondary)]">Program ještě nebyl načten. Použijte „Obnovit program“ nebo nechte denní synchronizaci pracovat automaticky.</p>}</div></div>
        <p className="mt-4 text-[10px] leading-relaxed text-[var(--color-text-secondary)]">This product uses the TMDB API but is not endorsed or certified by TMDB. Filmová metadata slouží pouze pro soukromé nekomerční plánování.</p>
    </section>;
}

function Metric({value,label,danger=false}:{value?:number;label:string;danger?:boolean}) { return <div className="rounded-lg border border-[var(--color-border)] px-2 py-1"><b className={`block ${danger&&value?'text-red-300':'text-white'}`}>{value??0}</b><span className="text-[10px] text-[var(--color-text-secondary)]">{label}</span></div>; }
function Priority({value}:{value:string}) { const labels:Record<string,string>={urgent:'urgentní',high:'vysoká',normal:'běžná',low:'nízká'};return <span className={`rounded px-2 py-0.5 text-[10px] ${value==='urgent'?'bg-red-500/15 text-red-200':value==='high'?'bg-amber-500/15 text-amber-200':'bg-white/5 text-[var(--color-text-secondary)]'}`}>{labels[value]??value}</span>; }
