import axios from 'axios';
import { LockKeyhole, Save, UsersRound } from 'lucide-react';
import { useEffect, useState } from 'react';

type Payload = { shared: { content: string } | null; mine: { content: string } | null };
export default function PersonNotesPanel({ personId }: { personId: number }) {
    const [shared, setShared] = useState(''); const [mine, setMine] = useState(''); const [saving, setSaving] = useState<'shared' | 'personal' | null>(null); const [message, setMessage] = useState('');
    const load = async () => { try { const response = await axios.get<Payload>(`/api/v1/people/${personId}/notes`); setShared(response.data.shared?.content ?? ''); setMine(response.data.mine?.content ?? ''); } catch (error: any) { setMessage(error?.response?.data?.message ?? 'Poznámky se nepodařilo načíst.'); } };
    useEffect(() => { void load(); }, [personId]);
    const save = async (visibility: 'shared' | 'personal') => { setSaving(visibility); setMessage(''); try { await axios.put(`/api/v1/people/${personId}/notes`, { visibility, content: visibility === 'shared' ? shared : mine }); setMessage(visibility === 'shared' ? 'Společná poznámka je uložená.' : 'Soukromá poznámka je uložená pouze pro vás.'); } catch (error: any) { setMessage(error?.response?.data?.message ?? 'Poznámku se nepodařilo uložit.'); } finally { setSaving(null); } };
    return <section className="rounded-3xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-5"><h2 className="text-sm font-semibold text-[var(--color-text-primary)]">Poznámky</h2><p className="mt-1 text-xs text-[var(--color-text-secondary)]">Společný kontext pro oba a vlastní soukromé poznámky jsou oddělené.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Editor icon={<UsersRound size={14}/>} label="Společná" hint="Viditelná pro oba" value={shared} onChange={setShared} onSave={() => save('shared')} saving={saving === 'shared'}/><Editor icon={<LockKeyhole size={14}/>} label="Moje soukromá" hint="Nikdy se nezobrazí partnerovi" value={mine} onChange={setMine} onSave={() => save('personal')} saving={saving === 'personal'} privateNote/></div>{message && <p role="status" className="mt-3 text-xs text-[var(--color-text-secondary)]">{message}</p>}</section>;
}
function Editor({ icon, label, hint, value, onChange, onSave, saving, privateNote = false }: { icon: React.ReactNode; label:string; hint:string; value:string; onChange:(v:string)=>void; onSave:()=>void; saving:boolean; privateNote?:boolean }) { return <div className={`rounded-2xl border p-3 ${privateNote ? 'border-violet-400/25 bg-violet-500/5' : 'border-[var(--color-border)] bg-[var(--color-bg-secondary)]'}`}><p className="flex items-center gap-1.5 text-xs font-medium text-[var(--color-text-primary)]">{icon}{label}</p><p className="mt-1 text-[10px] text-[var(--color-text-secondary)]">{hint}</p><textarea value={value} onChange={e => onChange(e.target.value)} rows={4} maxLength={10000} className="mt-2 w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-surface-muted)] p-2 text-xs text-[var(--color-text-primary)]"/><button disabled={saving} onClick={onSave} className="mt-2 inline-flex min-h-9 items-center gap-1.5 rounded-lg bg-[var(--color-accent)] px-3 text-xs font-medium text-[var(--color-text-primary)] disabled:opacity-50"><Save size={13}/>{saving ? 'Ukládám…' : 'Uložit'}</button></div>; }