import AppLayout from '@/Layouts/AppLayout';
import { Head, Link } from '@inertiajs/react';
import axios from 'axios';
import { ArrowLeft, CheckCircle2, Clock3, LocateFixed, MapPin, Navigation, NotebookPen, Plus, Trash2, Wallet } from 'lucide-react';
import { useEffect, useState } from 'react';

interface Activity { id:number; title:string; type:string; starts_at?:string; ends_at?:string; place_name?:string; latitude?:number; longitude?:number; status:string }
interface Entry { id:number; type:string; content?:string; amount?:number; currency?:string; recorded_at:string }
interface Data { trip:{id:number;name:string;currency:string}; day?:{date:string;title?:string}; activities:Activity[]; current?:Activity; next?:Activity; progress:number; journal:Entry[] }

export default function TripNow({ tripId }: { tripId:number }) {
    const [data,setData]=useState<Data|null>(null); const [note,setNote]=useState(''); const [busy,setBusy]=useState(false);
    const load=()=>axios.get(`/api/v1/trips/${tripId}/now`).then(r=>setData(r.data));
    useEffect(()=>{load();},[tripId]);
    const addNote=async()=>{if(!note.trim())return;setBusy(true);await axios.post(`/api/v1/trips/${tripId}/journal`,{type:'note',content:note});setNote('');await load();setBusy(false);};
    const addLocation=()=>navigator.geolocation?.getCurrentPosition(async p=>{await axios.post(`/api/v1/trips/${tripId}/journal`,{type:'location',latitude:p.coords.latitude,longitude:p.coords.longitude,content:'Uložená poloha'});await load();},()=>alert('Polohu se nepodařilo získat. Zkontrolujte oprávnění prohlížeče.'));
    const remove=async(id:number)=>{await axios.delete(`/api/v1/trips/${tripId}/journal/${id}`);setData(v=>v?{...v,journal:v.journal.filter(e=>e.id!==id)}:v);};
    if(!data)return <AppLayout><div className="flex min-h-64 items-center justify-center text-sm text-[var(--color-text-secondary)]">Načítám cestu…</div></AppLayout>;
    const focus=data.current??data.next;
    return <AppLayout><Head title={`Právě teď · ${data.trip.name}`}/><div className="mx-auto min-h-full max-w-3xl px-3 pb-24 pt-3 sm:px-6 sm:pt-6">
        <header className="mb-5 flex items-center gap-3"><Link href={`/trips/${tripId}/plan`} className="flex h-11 w-11 items-center justify-center rounded-xl border border-[var(--color-border)]"><ArrowLeft size={18}/></Link><div className="min-w-0 flex-1"><p className="text-[10px] uppercase tracking-widest text-[var(--color-accent)]">Právě teď</p><h1 className="truncate text-lg font-bold text-white">{data.trip.name}</h1></div><span className="text-xs text-[var(--color-text-secondary)]">{data.progress} %</span></header>
        <div className="mb-5 h-2 overflow-hidden rounded-full bg-[var(--color-bg-card)]"><div className="h-full rounded-full bg-[var(--color-accent)] transition-all" style={{width:`${data.progress}%`}}/></div>
        {focus?<section className="mb-5 rounded-3xl border border-[var(--color-accent)]/40 bg-gradient-to-br from-[var(--color-accent)]/20 to-[var(--color-bg-card)] p-5"><p className="text-[10px] uppercase tracking-widest text-[var(--color-accent)]">{data.current?'Probíhá':'Další zastávka'}</p><h2 className="mt-2 text-2xl font-bold text-white">{focus.title}</h2><div className="mt-3 flex flex-wrap gap-3 text-xs text-[var(--color-text-secondary)]">{focus.starts_at&&<span className="flex items-center gap-1"><Clock3 size={14}/>{focus.starts_at.slice(0,5)}</span>}{focus.place_name&&<span className="flex items-center gap-1"><MapPin size={14}/>{focus.place_name}</span>}</div>{focus.latitude&&focus.longitude&&<a href={`https://www.google.com/maps/dir/?api=1&destination=${focus.latitude},${focus.longitude}`} target="_blank" rel="noreferrer" className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[var(--color-accent)] text-sm font-medium text-white"><Navigation size={17}/>Navigovat</a>}</section>:<div className="mb-5 rounded-3xl border border-[var(--color-border)] p-8 text-center text-sm text-[var(--color-text-secondary)]"><CheckCircle2 className="mx-auto mb-2 text-green-400"/>Dnešní program je hotový nebo zatím prázdný.</div>}
        <section className="mb-5"><h2 className="mb-2 text-sm font-semibold text-white">Dnešní program</h2><div className="space-y-2">{data.activities.map(a=><div key={a.id} className={`flex items-center gap-3 rounded-2xl border border-[var(--color-border)] p-3 ${a.status==='done'?'opacity-50':''}`}><span className="w-12 text-xs text-[var(--color-text-secondary)]">{a.starts_at?.slice(0,5)??'—'}</span><span className="min-w-0 flex-1 truncate text-sm text-white">{a.title}</span>{a.status==='done'&&<CheckCircle2 size={16} className="text-green-400"/>}</div>)}</div></section>
        <section className="rounded-3xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-semibold text-white"><NotebookPen size={16}/>Cestovní deník</h2><button onClick={addLocation} title="Uložit aktuální polohu" className="flex h-10 w-10 items-center justify-center rounded-xl border border-[var(--color-border)]"><LocateFixed size={16}/></button></div><div className="flex gap-2"><input value={note} onChange={e=>setNote(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addNote();}} placeholder="Co si chcete zapamatovat?" className="min-h-11 min-w-0 flex-1 rounded-xl border border-[var(--color-border)] bg-[var(--color-bg-secondary)] px-3 text-sm text-white"/><button onClick={addNote} disabled={busy||!note.trim()} className="flex h-11 w-11 items-center justify-center rounded-xl bg-[var(--color-accent)] disabled:opacity-40"><Plus size={17}/></button></div><div className="mt-4 space-y-2">{data.journal.map(e=><div key={e.id} className="flex gap-3 rounded-xl bg-[var(--color-bg-secondary)] p-3"><div className="mt-0.5 text-[var(--color-accent)]">{e.type==='expense'?<Wallet size={15}/>:e.type==='location'?<MapPin size={15}/>:<NotebookPen size={15}/>}</div><div className="min-w-0 flex-1"><p className="text-xs text-white">{e.content||`${e.amount} ${e.currency}`}</p><p className="mt-1 text-[9px] text-[var(--color-text-secondary)]">{new Date(e.recorded_at).toLocaleString('cs-CZ')}</p></div><button onClick={()=>remove(e.id)} className="text-[var(--color-text-secondary)]"><Trash2 size={14}/></button></div>)}</div></section>
    </div></AppLayout>;
}
