import AppLayout from '@/Layouts/AppLayout';
import { Head, Link } from '@inertiajs/react';
import axios from 'axios';
import { FormEvent, useEffect, useState } from 'react';

interface Item { uuid:string; title:string; notes?:string; source_url?:string; kind:string; state:string; created_at:string; }
export default function TravelInbox() {
    const [items,setItems] = useState<Item[]>([]); const [title,setTitle] = useState(''); const [url,setUrl] = useState(''); const [spaceId,setSpaceId] = useState<number | null>(null); const [error,setError] = useState('');
    const load = async () => { try { const [inbox, calendar] = await Promise.all([axios.get('/api/v1/calendar/inbox'),axios.get('/api/v1/calendar/events')]); setItems(inbox.data ?? []); setSpaceId(calendar.data.spaces?.[0]?.id ?? null); } catch { setError('Inbox se nepodařilo načíst.'); } };
    useEffect(() => { load(); }, []);
    const add = async (e:FormEvent) => { e.preventDefault(); if (!spaceId) return; try { await axios.post('/api/v1/calendar/inbox',{gallery_space_id:spaceId,title,source_url:url || null,kind:url?'link':'idea'}); setTitle('');setUrl('');load(); } catch (e:any) { setError(e.response?.data?.message ?? 'Položku se nepodařilo uložit.'); } };
    const state = async (item:Item,next:string) => { await axios.patch(`/api/v1/calendar/inbox/${item.uuid}`,{state:next});load(); };
    return <AppLayout><Head title="Cestovní inbox"/><main className="mx-auto max-w-3xl p-4 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-xl font-semibold text-white">Cestovní inbox</h1><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Uložte nápad, odkaz nebo rezervaci a později jej přiřaďte k cestě či akci.</p></div><Link href="/calendar" className="text-sm text-[var(--color-accent)]">Kalendář</Link></div>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}<form onSubmit={add} className="mt-5 rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><div className="grid gap-2 sm:grid-cols-2"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nápad nebo rezervace" className="rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-white"/><input value={url} onChange={e=>setUrl(e.target.value)} type="url" placeholder="https://… (volitelné)" className="rounded-lg border border-[var(--color-border)] bg-black/10 p-2 text-white"/></div><button className="mt-3 rounded-lg bg-[var(--color-accent)] px-3 py-2 text-sm text-white">Uložit do inboxu</button></form><div className="mt-5 space-y-2">{items.map(item=><article key={item.uuid} className="rounded-xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4"><div className="flex gap-3"><div className="min-w-0 flex-1"><h2 className="font-medium text-white">{item.title}</h2>{item.notes&&<p className="mt-1 text-sm text-[var(--color-text-secondary)]">{item.notes}</p>}{item.source_url&&<a href={item.source_url} target="_blank" rel="noreferrer" className="mt-2 block truncate text-sm text-[var(--color-accent)]">{item.source_url}</a>}</div><span className="text-xs text-[var(--color-text-secondary)]">{item.state}</span></div><div className="mt-3 flex gap-2"><button onClick={()=>state(item,'assigned')} className="rounded border border-[var(--color-border)] px-2 py-1 text-xs text-white">Přiřazeno</button><button onClick={()=>state(item,'archived')} className="rounded border border-[var(--color-border)] px-2 py-1 text-xs text-[var(--color-text-secondary)]">Archivovat</button></div></article>)}{!items.length&&<p className="py-8 text-center text-sm text-[var(--color-text-secondary)]">Inbox je prázdný.</p>}</div></main></AppLayout>;
}
